# Generated by Django 4.0.6 on 2022-07-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cofkunionlocation',
            name='comments',
            field=models.ManyToManyField(to='core.cofkunioncomment'),
        ),
    ]
