# Generated by Django 4.0.6 on 2022-11-03 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('uploader', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cofkunionlocation',
            name='images',
            field=models.ManyToManyField(to='uploader.cofkunionimage'),
        ),
        migrations.AddField(
            model_name='cofkunionlocation',
            name='resources',
            field=models.ManyToManyField(to='core.cofkunionresource'),
        ),
        migrations.AddField(
            model_name='cofklocationresourcemap',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.cofkunionlocation'),
        ),
        migrations.AddField(
            model_name='cofklocationresourcemap',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cofkunionresource'),
        ),
        migrations.AddField(
            model_name='cofklocationcommentmap',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cofkunioncomment'),
        ),
        migrations.AddField(
            model_name='cofklocationcommentmap',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.cofkunionlocation'),
        ),
        migrations.AddField(
            model_name='cofkcollectlocationresource',
            name='upload',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='uploader.cofkcollectupload'),
        ),
        migrations.AddField(
            model_name='cofkcollectlocation',
            name='union_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='location.cofkunionlocation'),
        ),
        migrations.AddField(
            model_name='cofkcollectlocation',
            name='upload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uploader.cofkcollectupload'),
        ),
        migrations.AlterUniqueTogether(
            name='cofkcollectlocationresource',
            unique_together={('upload', 'resource_id')},
        ),
        migrations.AlterUniqueTogether(
            name='cofkcollectlocation',
            unique_together={('upload', 'location_id')},
        ),
    ]
