# Generated by Django 4.0.5 on 2022-06-17 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_remove_cofkcollectlocationresource_upload_id_and_more'),
        ('location', '0002_remove_cofkcollectlocation_union_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkcollectlocation',
            name='upload_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='uploader.cofkcollectupload'),
        ),
    ]
