# Generated by Django 4.0.6 on 2022-07-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('location', '0002_cofkunionlocation_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='cofkunionlocation',
            name='images',
            field=models.ManyToManyField(to='uploader.cofkunionimage'),
        ),
    ]
