# Generated by Django 4.0.6 on 2022-11-15 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cofkunionlocation',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='cofkunionlocation',
            name='resources',
        ),
    ]
