# Generated by Django 4.0.6 on 2023-01-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_alter_cofkunionqueryablework_work'),
        ('location', '0002_sync_old_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='cofkunionlocation',
            name='works',
            field=models.ManyToManyField(through='work.CofkWorkLocationMap', to='work.cofkunionwork'),
        ),
    ]
