# Generated by Django 4.0.5 on 2022-07-05 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_cofkcollectlocation_upload_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkcollectlocationresource',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.cofkcollectlocation'),
        ),
    ]
