# Generated by Django 4.0.6 on 2023-05-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_cofkunionlocation_works'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cofklocationcommentmap',
            index=models.Index(fields=['location', 'relationship_type'], name='cofk_locati_locatio_f571cd_idx'),
        ),
        migrations.AddIndex(
            model_name='cofklocationimagemap',
            index=models.Index(fields=['location', 'relationship_type'], name='cofk_locati_locatio_44073b_idx'),
        ),
        migrations.AddIndex(
            model_name='cofklocationresourcemap',
            index=models.Index(fields=['location', 'relationship_type'], name='cofk_locati_locatio_96468e_idx'),
        ),
    ]
