# Generated by Django 4.0.6 on 2023-06-14 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_cofklocationcommentmap_cofk_locati_locatio_f571cd_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cofkunionlocation',
            options={'permissions': [('export_file', 'Export csv/excel from search results')]},
        ),
    ]
