# Generated by Django 4.0.5 on 2022-07-05 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_alter_cofkcollectlocationresource_location_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cofkcollectlocationresource',
            old_name='location_id',
            new_name='location',
        ),
    ]
