# Generated by Django 4.0.6 on 2023-08-04 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_alter_cofkunionlocation_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayableLocation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('location.cofkunionlocation',),
        ),
    ]
