# Generated by Django 4.0.5 on 2022-07-05 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_rename_location_id_cofkcollectlocationresource_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cofkcollectlocationresource',
            old_name='upload_id',
            new_name='upload',
        ),
        migrations.AlterField(
            model_name='cofkcollectlocationresource',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='location.cofkcollectlocation'),
        ),
    ]
