# Generated by Django 4.0.5 on 2022-07-06 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_remove_cofkcollectlocationresource_upload_id_and_more'),
        ('location', '0006_rename_upload_id_cofkcollectlocationresource_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkcollectlocationresource',
            name='upload',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='uploader.cofkcollectupload'),
        ),
        migrations.AlterField(
            model_name='cofkunionlocation',
            name='editors_notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='cofkunionlocation',
            name='latitude',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cofkunionlocation',
            name='location_synonyms',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='cofkunionlocation',
            name='longitude',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
