# Generated by Django 4.0.6 on 2025-06-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_displayablelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cofkunionlocation',
            name='is_tombstone',
            field=models.BooleanField(default=False, help_text='Mark as tombstone instead of deleting'),
        ),
    ]
