# Generated by Django 5.2.15 on 2026-07-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_displayablelocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofklocationcommentmap',
            name='change_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofklocationcommentmap',
            name='creation_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofklocationimagemap',
            name='change_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofklocationimagemap',
            name='creation_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofklocationresourcemap',
            name='change_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofklocationresourcemap',
            name='creation_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofkunionlocation',
            name='change_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofkunionlocation',
            name='creation_user',
            field=models.CharField(max_length=254),
        ),
    ]
