# Generated by Django 5.2.15 on 2026-09-29 13:24

import core.helper.model_serv
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_alter_cofklocationcommentmap_change_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkunionlocation',
            name='uuid',
            field=models.UUIDField(blank=True, default=core.helper.model_serv.default_uuid, null=True),
        ),
        # records created in EMLO edit new had no uuid (emlo-project#866)
        migrations.RunSQL('UPDATE cofk_union_location SET uuid = gen_random_uuid() WHERE uuid IS NULL',
                          migrations.RunSQL.noop),
    ]
