# Generated by Django 4.0.5 on 2022-07-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_alter_cofkcollectlocationresource_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkcollectlocationresource',
            name='resource_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
