# Generated by Django 4.0.5 on 2022-07-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_alter_cofkcollectlocationresource_resource_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkcollectlocationresource',
            name='resource_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
