[project]
name = "site-edit-2"
version = "0.0.1"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]
dependencies = [
    'Django==5.2.15',
    'django-q2==1.6.1',
    'openpyxl~=3.1',
    'psycopg2~=2.9',
    'pycountry>=22.3',

    'selenium~=4.15',
    'django-compressor~=4.0',
    'django-sass-processor>=1.3',
    'libsass~=0.21.0',
    'Pillow~=11.0',
    'python-dateutil',
    'requests~=2.32',
    'gunicorn~=23.0',
    'beautifulsoup4~=4.11.2',
    'more-itertools~=9.1',
    'psutil~=5.9',
    'XlsxWriter~=3.1',
    'sqlalchemy~=2.0',

    'cllib~=0.2',
    'cllib-django~=0.0',

    'pylint~=3.0',
    'pylint-django~=2.5',
    'ipython==9.10.0'
]



[[project.authors]]
name = "somebody"


[build-system]
requires = ["setuptools", ]
build-backend = "setuptools.build_meta"


[project.scripts]
tweaker = "tweaker.__main__:main"

[tool.setuptools.packages.find]
exclude = [
    'devscript',
    'docker',
    'docs',
    'files',
]
