# Generated by Django 4.0.6 on 2022-12-22 14:26

import functools

import django.db.models.deletion
from django.db import migrations, models

import core.helper.model_serv


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CofkLookupCatalogue',
            fields=[
                ('catalogue_id', models.AutoField(primary_key=True, serialize=False)),
                ('catalogue_code', models.CharField(max_length=100, unique=True)),
                ('catalogue_name', models.CharField(max_length=500, unique=True)),
                ('is_in_union', models.IntegerField()),
                ('publish_status', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'cofk_lookup_catalogue',
            },
        ),
        migrations.CreateModel(
            name='CofkLookupDocumentType',
            fields=[
                ('document_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type_code', models.CharField(max_length=3, unique=True)),
                ('document_type_desc', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cofk_lookup_document_type',
            },
        ),
        migrations.CreateModel(
            name='CofkUnionComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('creation_timestamp', models.DateTimeField(blank=True, default=core.helper.model_serv.default_current_timestamp, null=True)),
                ('creation_user', models.CharField(max_length=50)),
                ('change_timestamp', models.DateTimeField(blank=True, default=core.helper.model_serv.default_current_timestamp, null=True)),
                ('change_user', models.CharField(max_length=50)),
                ('uuid', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cofk_union_comment',
            },
            bases=(models.Model, core.helper.model_serv.RecordTracker),
        ),
        migrations.CreateModel(
            name='CofkUnionImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_filename', models.TextField(blank=True, null=True)),
                ('creation_timestamp', models.DateTimeField(blank=True, default=core.helper.model_serv.default_current_timestamp, null=True)),
                ('creation_user', models.CharField(max_length=50)),
                ('change_timestamp', models.DateTimeField(blank=True, default=core.helper.model_serv.default_current_timestamp, null=True)),
                ('change_user', models.CharField(max_length=50)),
                ('thumbnail', models.TextField(blank=True, null=True)),
                ('can_be_displayed', models.CharField(max_length=1)),
                ('display_order', models.IntegerField(default=1)),
                ('licence_details', models.TextField()),
                ('licence_url', models.CharField(max_length=2000)),
                ('credits', models.CharField(max_length=2000)),
                ('uuid', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cofk_union_image',
            },
            bases=(models.Model, core.helper.model_serv.RecordTracker),
        ),
        migrations.CreateModel(
            name='CofkUnionNationality',
            fields=[
                ('nationality_id', models.AutoField(primary_key=True, serialize=False)),
                ('nationality_desc', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cofk_union_nationality',
            },
        ),
        migrations.CreateModel(
            name='CofkUnionOrgType',
            fields=[
                ('org_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('org_type_desc', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cofk_union_org_type',
            },
        ),
        migrations.CreateModel(
            name='CofkUnionRelationshipType',
            fields=[
                ('relationship_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('desc_left_to_right', models.CharField(max_length=200)),
                ('desc_right_to_left', models.CharField(max_length=200)),
                ('creation_timestamp', models.DateTimeField(blank=True, default=core.helper.model_serv.default_current_timestamp, null=True)),
                ('creation_user', models.CharField(max_length=50)),
                ('change_timestamp', models.DateTimeField(blank=True, default=core.helper.model_serv.default_current_timestamp, null=True)),
                ('change_user', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cofk_union_relationship_type',
            },
            bases=(models.Model, core.helper.model_serv.RecordTracker),
        ),
        migrations.CreateModel(
            name='CofkUnionResource',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False)),
                ('resource_name', models.TextField()),
                ('resource_details', models.TextField()),
                ('resource_url', models.TextField()),
                ('creation_timestamp', models.DateTimeField(blank=True, default=core.helper.model_serv.default_current_timestamp, null=True)),
                ('creation_user', models.CharField(max_length=50)),
                ('change_timestamp', models.DateTimeField(blank=True, default=core.helper.model_serv.default_current_timestamp, null=True)),
                ('change_user', models.CharField(max_length=50)),
                ('uuid', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cofk_union_resource',
            },
            bases=(models.Model, core.helper.model_serv.RecordTracker),
        ),
        migrations.CreateModel(
            name='CofkUnionRoleCategory',
            fields=[
                ('role_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_category_desc', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cofk_union_role_category',
            },
        ),
        migrations.CreateModel(
            name='CofkUnionSpeedEntryText',
            fields=[
                ('speed_entry_text_id', models.AutoField(primary_key=True, serialize=False)),
                ('object_type', models.CharField(max_length=30)),
                ('speed_entry_text', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'cofk_union_speed_entry_text',
            },
        ),
        migrations.CreateModel(
            name='CofkUnionSubject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_desc', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cofk_union_subject',
            },
        ),
        migrations.CreateModel(
            name='CofkUserSavedQuery',
            fields=[
                ('query_id', models.AutoField(primary_key=True, serialize=False)),
                ('query_class', models.CharField(max_length=100)),
                ('query_method', models.CharField(max_length=100)),
                ('query_title', models.TextField()),
                ('query_order_by', models.CharField(max_length=100)),
                ('query_sort_descending', models.SmallIntegerField()),
                ('query_entries_per_page', models.SmallIntegerField()),
                ('query_record_layout', models.CharField(max_length=12)),
                ('query_menu_item_name', models.TextField(blank=True, null=True)),
                ('creation_timestamp', models.DateTimeField(blank=True, default=core.helper.model_serv.default_current_timestamp, null=True)),
            ],
            options={
                'db_table': 'cofk_user_saved_query',
            },
        ),
        migrations.CreateModel(
            name='CopyCofkUnionQueryableWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iwork_id', models.IntegerField(blank=True, null=True)),
                ('work_id', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_of_work_std', models.DateField(blank=True, null=True)),
                ('date_of_work_std_year', models.IntegerField(blank=True, null=True)),
                ('date_of_work_std_month', models.IntegerField(blank=True, null=True)),
                ('date_of_work_std_day', models.IntegerField(blank=True, null=True)),
                ('date_of_work_as_marked', models.CharField(blank=True, max_length=250, null=True)),
                ('date_of_work_inferred', models.SmallIntegerField(blank=True, null=True)),
                ('date_of_work_uncertain', models.SmallIntegerField(blank=True, null=True)),
                ('date_of_work_approx', models.SmallIntegerField(blank=True, null=True)),
                ('creators_searchable', models.TextField(blank=True, null=True)),
                ('creators_for_display', models.TextField(blank=True, null=True)),
                ('authors_as_marked', models.TextField(blank=True, null=True)),
                ('notes_on_authors', models.TextField(blank=True, null=True)),
                ('authors_inferred', models.SmallIntegerField(blank=True, null=True)),
                ('authors_uncertain', models.SmallIntegerField(blank=True, null=True)),
                ('addressees_searchable', models.TextField(blank=True, null=True)),
                ('addressees_for_display', models.TextField(blank=True, null=True)),
                ('addressees_as_marked', models.TextField(blank=True, null=True)),
                ('addressees_inferred', models.SmallIntegerField(blank=True, null=True)),
                ('addressees_uncertain', models.SmallIntegerField(blank=True, null=True)),
                ('places_from_searchable', models.TextField(blank=True, null=True)),
                ('places_from_for_display', models.TextField(blank=True, null=True)),
                ('origin_as_marked', models.TextField(blank=True, null=True)),
                ('origin_inferred', models.SmallIntegerField(blank=True, null=True)),
                ('origin_uncertain', models.SmallIntegerField(blank=True, null=True)),
                ('places_to_searchable', models.TextField(blank=True, null=True)),
                ('places_to_for_display', models.TextField(blank=True, null=True)),
                ('destination_as_marked', models.TextField(blank=True, null=True)),
                ('destination_inferred', models.SmallIntegerField(blank=True, null=True)),
                ('destination_uncertain', models.SmallIntegerField(blank=True, null=True)),
                ('manifestations_searchable', models.TextField(blank=True, null=True)),
                ('manifestations_for_display', models.TextField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('people_mentioned', models.TextField(blank=True, null=True)),
                ('images', models.TextField(blank=True, null=True)),
                ('related_resources', models.TextField(blank=True, null=True)),
                ('language_of_work', models.CharField(blank=True, max_length=255, null=True)),
                ('work_is_translation', models.SmallIntegerField(blank=True, null=True)),
                ('flags', models.TextField(blank=True, null=True)),
                ('edit_status', models.CharField(blank=True, max_length=3, null=True)),
                ('general_notes', models.TextField(blank=True, null=True)),
                ('original_catalogue', models.CharField(blank=True, max_length=100, null=True)),
                ('accession_code', models.CharField(blank=True, max_length=1000, null=True)),
                ('work_to_be_deleted', models.SmallIntegerField(blank=True, null=True)),
                ('change_timestamp', models.DateTimeField(blank=True, default=core.helper.model_serv.default_current_timestamp, null=True)),
                ('change_user', models.CharField(blank=True, max_length=50, null=True)),
                ('drawer', models.CharField(blank=True, max_length=50, null=True)),
                ('editors_notes', models.TextField(blank=True, null=True)),
                ('manifestation_type', models.CharField(blank=True, max_length=50, null=True)),
                ('original_notes', models.TextField(blank=True, null=True)),
                ('relevant_to_cofk', models.CharField(blank=True, max_length=1, null=True)),
                ('subjects', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'copy_cofk_union_queryable_work',
            },
        ),
        migrations.CreateModel(
            name='Iso639LanguageCode',
            fields=[
                ('code_639_3', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('code_639_1', models.CharField(max_length=2)),
                ('language_name', models.CharField(max_length=100)),
                ('language_id', models.IntegerField(default=functools.partial(core.helper.model_serv.next_seq_safe, *('iso_639_language_codes_id_seq',), **{}), unique=True)),
            ],
            options={
                'db_table': 'iso_639_language_codes',
            },
        ),
        migrations.CreateModel(
            name='CofkUnionFavouriteLanguage',
            fields=[
                ('language_code', models.OneToOneField(db_column='language_code', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.iso639languagecode')),
            ],
            options={
                'db_table': 'cofk_union_favourite_language',
            },
        ),
        migrations.CreateModel(
            name='CofkUserSavedQuerySelection',
            fields=[
                ('selection_id', models.AutoField(primary_key=True, serialize=False)),
                ('column_name', models.CharField(max_length=100)),
                ('column_value', models.CharField(max_length=500)),
                ('op_name', models.CharField(max_length=100)),
                ('op_value', models.CharField(max_length=100)),
                ('column_value2', models.CharField(max_length=500)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.cofkusersavedquery')),
            ],
            options={
                'db_table': 'cofk_user_saved_query_selection',
            },
        ),
    ]
