# Generated by Django 4.0.6 on 2022-07-08 12:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CofkUnionComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('creation_timestamp', models.DateTimeField(auto_now=True)),
                ('change_timestamp', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
            ],
            options={
                'db_table': 'cofk_union_comment',
            },
        ),
        migrations.CreateModel(
            name='CofkUnionRelationshipType',
            fields=[
                ('relationship_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('desc_left_to_right', models.CharField(default='', max_length=200)),
                ('desc_right_to_left', models.CharField(default='', max_length=200)),
                ('creation_timestamp', models.DateTimeField(auto_now=True)),
                ('change_timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cofk_union_relationship_type',
            },
        ),
        migrations.CreateModel(
            name='CofkUnionResource',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False)),
                ('resource_name', models.TextField(default='')),
                ('resource_details', models.TextField(default='')),
                ('resource_url', models.TextField(default='')),
                ('creation_timestamp', models.DateTimeField(auto_now=True)),
                ('change_timestamp', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
            ],
            options={
                'db_table': 'cofk_union_resource',
            },
        ),
        migrations.CreateModel(
            name='CofkUnionRelationship',
            fields=[
                ('relationship_id', models.AutoField(primary_key=True, serialize=False)),
                ('left_table_name', models.CharField(max_length=100)),
                ('left_id_value', models.CharField(max_length=100)),
                ('right_table_name', models.CharField(max_length=100)),
                ('right_id_value', models.CharField(max_length=100)),
                ('relationship_valid_from', models.DateTimeField()),
                ('relationship_valid_till', models.DateTimeField()),
                ('creation_timestamp', models.DateTimeField(auto_now=True)),
                ('change_timestamp', models.DateTimeField(auto_now=True)),
                ('relationship_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.cofkunionrelationshiptype')),
            ],
            options={
                'db_table': 'cofk_union_relationship',
            },
        ),
    ]
