# Generated by Django 4.0.6 on 2022-12-16 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProActivity',
        ),
        migrations.DeleteModel(
            name='ProActivityRelation',
        ),
        migrations.DeleteModel(
            name='ProAssertion',
        ),
        migrations.DeleteModel(
            name='ProIngestMapV2',
        ),
        migrations.DeleteModel(
            name='ProIngestV8',
        ),
        migrations.DeleteModel(
            name='ProIngestV8Toreview',
        ),
        migrations.DeleteModel(
            name='ProLocation',
        ),
        migrations.DeleteModel(
            name='ProPeopleCheck',
        ),
        migrations.DeleteModel(
            name='ProPrimaryPerson',
        ),
        migrations.DeleteModel(
            name='ProRelationship',
        ),
        migrations.DeleteModel(
            name='ProRoleInActivity',
        ),
        migrations.DeleteModel(
            name='ProTextualSource',
        ),
    ]
