# Generated by Django 4.0.6 on 2022-09-01 13:00

import core.helper.model_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkunioncomment',
            name='change_timestamp',
            field=models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True),
        ),
        migrations.AlterField(
            model_name='cofkunioncomment',
            name='creation_timestamp',
            field=models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True),
        ),
        migrations.AlterField(
            model_name='cofkunionrelationship',
            name='change_timestamp',
            field=models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True),
        ),
        migrations.AlterField(
            model_name='cofkunionrelationship',
            name='creation_timestamp',
            field=models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True),
        ),
        migrations.AlterField(
            model_name='cofkunionrelationshiptype',
            name='change_timestamp',
            field=models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True),
        ),
        migrations.AlterField(
            model_name='cofkunionrelationshiptype',
            name='creation_timestamp',
            field=models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True),
        ),
        migrations.AlterField(
            model_name='cofkunionresource',
            name='change_timestamp',
            field=models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True),
        ),
        migrations.AlterField(
            model_name='cofkunionresource',
            name='creation_timestamp',
            field=models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True),
        ),
        migrations.AlterField(
            model_name='copycofkunionqueryablework',
            name='change_timestamp',
            field=models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True),
        ),
        migrations.AlterField(
            model_name='proactivity',
            name='change_timestamp',
            field=models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True),
        ),
        migrations.AlterField(
            model_name='proactivity',
            name='creation_timestamp',
            field=models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True),
        ),
        migrations.AlterField(
            model_name='proassertion',
            name='change_timestamp',
            field=models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True),
        ),
        migrations.AlterField(
            model_name='prolocation',
            name='change_timestamp',
            field=models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True),
        ),
        migrations.AlterField(
            model_name='proprimaryperson',
            name='change_timestamp',
            field=models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True),
        ),
        migrations.AlterField(
            model_name='prorelationship',
            name='change_timestamp',
            field=models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True),
        ),
        migrations.AlterField(
            model_name='proroleinactivity',
            name='change_timestamp',
            field=models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True),
        ),
        migrations.AlterField(
            model_name='protextualsource',
            name='change_timestamp',
            field=models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True),
        ),
        migrations.AlterField(
            model_name='protextualsource',
            name='creation_timestamp',
            field=models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True),
        ),
    ]
