# Generated by Django 4.0.6 on 2022-12-20 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sync_old_schema'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CofkUnionRelationship',
        ),
    ]
