# Generated by Django 4.0.6 on 2023-03-07 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_seq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cofklookupcatalogue',
            options={'ordering': ['catalogue_name']},
        ),
        migrations.AlterModelOptions(
            name='cofkunionrolecategory',
            options={'ordering': ['role_category_desc']},
        ),
    ]
