# Generated by Django 4.0.6 on 2023-03-20 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_cofklookupcatalogue_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cofkusersavedquery',
            table='cofk_user_saved_queries',
        ),
    ]
