# Generated by Django 4.0.6 on 2023-05-15 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_cofkusersavedquery_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CopyCofkUnionQueryableWork',
        ),
    ]
