# Generated by Django 4.0.6 on 2023-06-15 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_copycofkunionqueryablework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkunionfavouritelanguage',
            name='language_code',
            field=models.OneToOneField(db_column='language_code', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.iso639languagecode'),
        ),
    ]
