# Generated by Django 4.0.6 on 2024-10-03 11:08

from django.db import migrations, models

import core.helper.model_serv


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_cofkunionfavouritelanguage_language_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeHistory',
            fields=[
                ('merge_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('new_id', models.IntegerField()),
                ('new_name', models.TextField()),
                ('org_id', models.IntegerField()),
                ('org_name', models.TextField()),
                ('model_class_name', models.CharField(max_length=100)),
                ('creation_timestamp', models.DateTimeField(blank=True, default=core.helper.model_serv.default_current_timestamp, null=True)),
                ('creation_user', models.CharField(max_length=50)),
                ('change_timestamp', models.DateTimeField(blank=True, default=core.helper.model_serv.default_current_timestamp, null=True)),
                ('change_user', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'merge_history',
            },
            bases=(models.Model, core.helper.model_serv.RecordTracker),
        ),
    ]
