# Generated by Django 4.0.6 on 2024-10-03 11:52

from django.db import migrations, models

import core.helper.model_serv


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_cofkunionfavouritelanguage_language_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeHistory',
            fields=[
                ('merge_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('new_id', models.CharField(max_length=250)),
                ('new_name', models.TextField()),
                ('old_id', models.CharField(max_length=250)),
                ('old_name', models.TextField()),
                ('model_class_name', models.CharField(max_length=200)),
                ('creation_timestamp', models.DateTimeField(blank=True, default=core.helper.model_serv.default_current_timestamp, null=True)),
                ('creation_user', models.CharField(max_length=50)),
                ('change_timestamp', models.DateTimeField(blank=True, default=core.helper.model_serv.default_current_timestamp, null=True)),
                ('change_user', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'merge_history',
            },
            bases=(models.Model, core.helper.model_serv.RecordTracker),
        ),
        migrations.AddIndex(
            model_name='mergehistory',
            index=models.Index(fields=['model_class_name', 'new_id'], name='merge_histo_model_c_a03701_idx'),
        ),
    ]
