# Generated by Django 4.0.6 on 2025-01-29 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_alter_cofkunionfavouritelanguage_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cofklookupcatalogue',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogues', to=settings.AUTH_USER_MODEL),
        ),
    ]
