# Generated by Django 4.0.6 on 2026-04-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_iso639languagecode_language_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CofkResourceDescriptor',
            fields=[
                ('descriptor_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('related_to', models.CharField(choices=[('People', 'People'), ('Places', 'Places'), ('Repositories', 'Repositories'), ('Works', 'Works')], max_length=20)),
            ],
            options={
                'db_table': 'cofk_resource_descriptor',
                'ordering': ['description'],
                'unique_together': {('description', 'related_to')},
            },
        ),
    ]
