# Generated by Django 5.2.15 on 2026-07-16 14:27

import core.helper.model_serv
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_populate_resource_descriptors'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeHistory',
            fields=[
                ('merge_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('new_id', models.CharField(max_length=100)),
                ('new_name', models.TextField()),
                ('new_display_id', models.CharField(max_length=100)),
                ('old_id', models.CharField(max_length=100)),
                ('old_name', models.TextField()),
                ('old_display_id', models.CharField(max_length=100)),
                ('model_class_name', models.CharField(max_length=100)),
                ('creation_timestamp', models.DateTimeField(blank=True, default=core.helper.model_serv.default_current_timestamp, null=True)),
                ('creation_user', models.CharField(max_length=50)),
                ('change_timestamp', models.DateTimeField(blank=True, default=core.helper.model_serv.default_current_timestamp, null=True)),
                ('change_user', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'merge_history',
                'indexes': [models.Index(fields=['model_class_name', 'old_id'], name='merge_histo_model_c_bb8bcc_idx')],
            },
            bases=(models.Model, core.helper.model_serv.RecordTracker),
        ),
    ]
