# Generated by Django 5.2.15 on 2026-07-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_widen_saved_query_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkunioncomment',
            name='change_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofkunioncomment',
            name='creation_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofkunionimage',
            name='change_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofkunionimage',
            name='creation_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofkunionrelationshiptype',
            name='change_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofkunionrelationshiptype',
            name='creation_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofkunionresource',
            name='change_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofkunionresource',
            name='creation_user',
            field=models.CharField(max_length=254),
        ),
    ]
