# Generated by Django 5.2.15 on 2026-09-29 13:24

import core.helper.model_serv
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_cofkusersavedquery_username_cascade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkunioncomment',
            name='uuid',
            field=models.UUIDField(blank=True, default=core.helper.model_serv.default_uuid, null=True),
        ),
        migrations.AlterField(
            model_name='cofkunionimage',
            name='uuid',
            field=models.UUIDField(blank=True, default=core.helper.model_serv.default_uuid, null=True),
        ),
        migrations.AlterField(
            model_name='cofkunionresource',
            name='uuid',
            field=models.UUIDField(blank=True, default=core.helper.model_serv.default_uuid, null=True),
        ),
        # records created in EMLO edit new had no uuid (emlo-project#866)
        migrations.RunSQL('UPDATE cofk_union_comment SET uuid = gen_random_uuid() WHERE uuid IS NULL',
                          migrations.RunSQL.noop),
        # records created in EMLO edit new had no uuid (emlo-project#866)
        migrations.RunSQL('UPDATE cofk_union_image SET uuid = gen_random_uuid() WHERE uuid IS NULL',
                          migrations.RunSQL.noop),
        # records created in EMLO edit new had no uuid (emlo-project#866)
        migrations.RunSQL('UPDATE cofk_union_resource SET uuid = gen_random_uuid() WHERE uuid IS NULL',
                          migrations.RunSQL.noop),
    ]
