import uuid as uuid
from django.db import models


class CofkUnionManifestation(models.Model):
    manifestation_id = models.CharField(max_length=100, primary_key=True)
    manifestation_type = models.CharField(max_length=3, null=False, default='')
    id_number_or_shelfmark = models.CharField(max_length=500)
    printed_edition_details = models.TextField()
    paper_size = models.CharField(max_length=500)
    paper_type_or_watermark = models.CharField(max_length=500)
    number_of_pages_of_document = models.IntegerField()
    number_of_pages_of_text = models.IntegerField()
    seal = models.CharField(max_length=500)
    postage_marks = models.CharField(max_length=500)
    endorsements = models.TextField()
    non_letter_enclosures = models.TextField()
    manifestation_creation_calendar = models.CharField(max_length=2, null=False, default='U')
    manifestation_creation_date = models.DateField()
    manifestation_creation_date_gregorian = models.DateField()
    manifestation_creation_date_year = models.IntegerField()
    manifestation_creation_date_month = models.IntegerField()
    manifestation_creation_date_day = models.IntegerField()
    manifestation_creation_date_inferred = models.SmallIntegerField(null=False, default=0)
    manifestation_creation_date_uncertain = models.SmallIntegerField(null=False, default=0)
    manifestation_creation_date_approx = models.SmallIntegerField(null=False, default=0)
    manifestation_is_translation = models.SmallIntegerField(null=False, default=0)
    language_of_manifestation = models.CharField(max_length=255)
    address = models.TextField()
    manifestation_incipit = models.TextField()
    manifestation_excipit = models.TextField()
    manifestation_ps = models.TextField()
    creation_timestamp = models.DateTimeField(auto_now=True)
    change_timestamp = models.DateTimeField(auto_now=True)
    manifestation_creation_date2_year = models.IntegerField()
    manifestation_creation_date2_month = models.IntegerField()
    manifestation_creation_date2_day = models.IntegerField()
    manifestation_creation_date_is_range = models.SmallIntegerField(null=False, default=0)
    manifestation_creation_date_as_marked = models.CharField(max_length=250)
    opened = models.CharField(max_length=3, null=False, default='o')
    uuid = models.UUIDField(default=uuid.uuid4)
    routing_mark_stamp = models.TextField()
    routing_mark_ms = models.TextField()
    handling_instructions = models.TextField()
    stored_folded = models.CharField(max_length=20)
    postage_costs_as_marked = models.CharField(max_length=500)
    postage_costs = models.CharField(max_length=500)
    non_delivery_reason = models.CharField(max_length=500)
    date_of_receipt_as_marked = models.CharField(max_length=500)
    manifestation_receipt_calendar = models.CharField(max_length=2, null=False, default='U')
    manifestation_receipt_date = models.DateField()
    manifestation_receipt_date_gregorian = models.DateField()
    manifestation_receipt_date_year = models.IntegerField()
    manifestation_receipt_date_month = models.IntegerField()
    manifestation_receipt_date_day = models.IntegerField()
    manifestation_receipt_date_inferred = models.SmallIntegerField(null=False, default=0)
    manifestation_receipt_date_uncertain = models.SmallIntegerField(null=False, default=0)
    manifestation_receipt_date_approx = models.SmallIntegerField(null=False, default=0)
    manifestation_receipt_date2_year = models.IntegerField()
    manifestation_receipt_date2_month = models.IntegerField()
    manifestation_receipt_date2_day = models.IntegerField()
    manifestation_receipt_date_is_range = models.SmallIntegerField(null=False, default=0)
    accompaniments = models.TextField()


class CofkCollectManifestation(models.Model):
    upload_id = models.ForeignKey("uploader.CofkCollectUpload", null=False, on_delete=models.CASCADE)
    manifestation_id = models.AutoField(primary_key=True)
    union_manifestation_id = models.OneToOneField("CofkUnionManifestation", null=True, on_delete=models.CASCADE)
    manifestation_type = models.CharField(max_length=3, null=False, default='')
    repository_id = models.IntegerField()
    id_number_or_shelfmark = models.CharField(max_length=500)
    printed_edition_details = models.TextField()
    manifestation_notes = models.TextField()
    image_filenames = models.TextField()
    upload_name = models.CharField(max_length=254)
    _id = models.CharField(max_length=32)


class CofkUnionLanguageOfManifestation(models.Model):
    manifestation_id = models.OneToOneField("CofkUnionManifestation", on_delete=models.CASCADE)
    language_code = models.ForeignKey("uploader.Iso639LanguageCode", on_delete=models.CASCADE, null=False)
    notes = models.CharField(max_length=100)
