# Generated by Django 4.0.6 on 2025-02-11 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CofkSuggestions',
            fields=[
                ('suggestion_id', models.AutoField(primary_key=True, serialize=False)),
                ('suggestion_new', models.BooleanField(default=True)),
                ('suggestion_type', models.CharField(max_length=200)),
                ('suggestion_suggestion', models.TextField()),
                ('suggestion_status', models.CharField(default='Pending', max_length=256)),
                ('suggestion_created_at', models.DateTimeField(auto_now_add=True)),
                ('suggestion_updated_at', models.DateTimeField(auto_now=True)),
                ('suggestion_resolved_at', models.DateTimeField(blank=True, null=True)),
                ('suggestion_author', models.CharField(default='Anonymous', max_length=256)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestion_relation', to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'cofk_union_suggestions',
            },
        ),
    ]
