# Generated by Django 4.0.6 on 2025-02-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofksuggestions',
            name='suggestion_status',
            field=models.CharField(default='New', max_length=256),
        ),
    ]
