# Generated by Django 4.0.6 on 2025-02-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0002_alter_cofksuggestions_suggestion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cofksuggestions',
            name='suggestion_related_record_int',
            field=models.IntegerField(default=-1),
        ),
    ]
