# Generated by Django 4.0.6 on 2025-02-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0003_cofksuggestions_suggestion_related_record_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofksuggestions',
            name='suggestion_related_record_int',
            field=models.IntegerField(),
        ),
    ]
