# Generated by Django 4.0.6 on 2025-02-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0004_alter_cofksuggestions_suggestion_related_record_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofksuggestions',
            name='suggestion_related_record_int',
            field=models.IntegerField(null=True),
        ),
    ]
