# Generated by Django 4.0.6 on 2025-02-26 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suggestions', '0005_alter_cofksuggestions_suggestion_related_record_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofksuggestions',
            name='suggestion_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cofksuggestions',
            name='suggestion_related_record_int',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
