# Generated by Django 4.0.6 on 2022-09-29 23:08

import core.helper.model_utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uploader.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CofkCollectStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_desc', models.CharField(max_length=100)),
                ('editable', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'cofk_collect_status',
            },
        ),
        migrations.CreateModel(
            name='CofkCollectToolUser',
            fields=[
                ('tool_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('tool_user_email', models.CharField(max_length=100, unique=True)),
                ('tool_user_surname', models.CharField(max_length=100)),
                ('tool_user_forename', models.CharField(max_length=100)),
                ('tool_user_pw', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cofk_collect_tool_user',
            },
        ),
        migrations.CreateModel(
            name='CofkLookupCatalogue',
            fields=[
                ('catalogue_id', models.AutoField(primary_key=True, serialize=False)),
                ('catalogue_code', models.CharField(max_length=100, unique=True)),
                ('catalogue_name', models.CharField(max_length=500, unique=True)),
                ('is_in_union', models.IntegerField()),
                ('publish_status', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'cofk_lookup_catalogue',
            },
        ),
        migrations.CreateModel(
            name='CofkReportGroup',
            fields=[
                ('report_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_group_title', models.TextField(blank=True, null=True)),
                ('report_group_order', models.IntegerField()),
                ('on_main_reports_menu', models.IntegerField()),
                ('report_group_code', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cofk_report_group',
            },
        ),
        migrations.CreateModel(
            name='CofkUnionAuditLiteral',
            fields=[
                ('audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('change_timestamp', models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True)),
                ('change_user', models.CharField(max_length=50)),
                ('change_type', models.CharField(max_length=3)),
                ('table_name', models.CharField(max_length=100)),
                ('key_value_text', models.CharField(max_length=100)),
                ('key_value_integer', models.IntegerField(blank=True, null=True)),
                ('key_decode', models.TextField(blank=True, null=True)),
                ('column_name', models.CharField(max_length=100)),
                ('new_column_value', models.TextField(blank=True, null=True)),
                ('old_column_value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cofk_union_audit_literal',
            },
        ),
        migrations.CreateModel(
            name='CofkUnionAuditRelationship',
            fields=[
                ('audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('change_timestamp', models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True)),
                ('change_user', models.CharField(max_length=50)),
                ('change_type', models.CharField(max_length=3)),
                ('left_table_name', models.CharField(max_length=100)),
                ('left_id_value_new', models.CharField(max_length=100)),
                ('left_id_decode_new', models.TextField()),
                ('left_id_value_old', models.CharField(max_length=100)),
                ('left_id_decode_old', models.TextField()),
                ('relationship_type', models.CharField(max_length=100)),
                ('relationship_decode_left_to_right', models.CharField(max_length=100)),
                ('relationship_decode_right_to_left', models.CharField(max_length=100)),
                ('right_table_name', models.CharField(max_length=100)),
                ('right_id_value_new', models.CharField(max_length=100)),
                ('right_id_decode_new', models.TextField()),
                ('right_id_value_old', models.CharField(max_length=100)),
                ('right_id_decode_old', models.TextField()),
            ],
            options={
                'db_table': 'cofk_union_audit_relationship',
            },
        ),
        migrations.CreateModel(
            name='CofkUnionImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_filename', models.TextField(blank=True, null=True)),
                ('creation_timestamp', models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True)),
                ('creation_user', models.CharField(max_length=50)),
                ('change_timestamp', models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True)),
                ('change_user', models.CharField(max_length=50)),
                ('thumbnail', models.TextField(blank=True, null=True)),
                ('can_be_displayed', models.CharField(max_length=1)),
                ('display_order', models.IntegerField()),
                ('licence_details', models.TextField()),
                ('licence_url', models.CharField(max_length=2000)),
                ('credits', models.CharField(max_length=2000)),
                ('uuid', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cofk_union_image',
            },
            bases=(models.Model, core.helper.model_utils.RecordTracker),
        ),
        migrations.CreateModel(
            name='CofkUnionOrgType',
            fields=[
                ('org_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('org_type_desc', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cofk_union_org_type',
            },
        ),
        migrations.CreateModel(
            name='CofkUnionRoleCategory',
            fields=[
                ('role_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_category_desc', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cofk_union_role_category',
            },
        ),
        migrations.CreateModel(
            name='CofkUnionSubject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_desc', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cofk_union_subject',
            },
        ),
        migrations.CreateModel(
            name='CofkUserSavedQuery',
            fields=[
                ('query_id', models.AutoField(primary_key=True, serialize=False)),
                ('query_class', models.CharField(max_length=100)),
                ('query_method', models.CharField(max_length=100)),
                ('query_title', models.TextField()),
                ('query_order_by', models.CharField(max_length=100)),
                ('query_sort_descending', models.SmallIntegerField()),
                ('query_entries_per_page', models.SmallIntegerField()),
                ('query_record_layout', models.CharField(max_length=12)),
                ('query_menu_item_name', models.TextField(blank=True, null=True)),
                ('creation_timestamp', models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True)),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cofk_user_saved_query',
            },
        ),
        migrations.CreateModel(
            name='Iso639LanguageCode',
            fields=[
                ('code_639_3', models.CharField(max_length=3)),
                ('code_639_1', models.CharField(max_length=2)),
                ('language_name', models.CharField(max_length=100)),
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'iso_639_language_codes',
            },
        ),
        migrations.CreateModel(
            name='CofkUnionFavouriteLanguage',
            fields=[
                ('language_code', models.OneToOneField(db_column='language_code', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='uploader.iso639languagecode')),
            ],
            options={
                'db_table': 'cofk_union_favourite_language',
            },
        ),
        migrations.CreateModel(
            name='CofkUserSavedQuerySelection',
            fields=[
                ('selection_id', models.AutoField(primary_key=True, serialize=False)),
                ('column_name', models.CharField(max_length=100)),
                ('column_value', models.CharField(max_length=500)),
                ('op_name', models.CharField(max_length=100)),
                ('op_value', models.CharField(max_length=100)),
                ('column_value2', models.CharField(max_length=500)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='uploader.cofkusersavedquery')),
            ],
            options={
                'db_table': 'cofk_user_saved_query_selection',
            },
        ),
        migrations.CreateModel(
            name='CofkReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_title', models.TextField(blank=True, null=True)),
                ('class_name', models.CharField(blank=True, max_length=40, null=True)),
                ('method_name', models.CharField(blank=True, max_length=40, null=True)),
                ('has_csv_option', models.BooleanField(default=False)),
                ('is_dummy_option', models.BooleanField(default=False)),
                ('report_code', models.CharField(blank=True, max_length=100, null=True)),
                ('parm_list', models.TextField(blank=True, null=True)),
                ('parm_titles', models.TextField(blank=True, null=True)),
                ('prompt_for_parms', models.SmallIntegerField()),
                ('default_parm_values', models.TextField(blank=True, null=True)),
                ('parm_methods', models.TextField(blank=True, null=True)),
                ('report_help', models.TextField(blank=True, null=True)),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.cofkmenu')),
                ('report_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='uploader.cofkreportgroup')),
            ],
            options={
                'db_table': 'cofk_report',
            },
        ),
        migrations.CreateModel(
            name='CofkCollectUpload',
            fields=[
                ('upload_id', models.AutoField(primary_key=True, serialize=False)),
                ('upload_username', models.CharField(max_length=100)),
                ('upload_description', models.TextField(blank=True, null=True)),
                ('upload_timestamp', models.DateTimeField()),
                ('total_works', models.IntegerField()),
                ('works_accepted', models.IntegerField()),
                ('works_rejected', models.IntegerField()),
                ('uploader_email', models.CharField(max_length=250)),
                ('_id', models.CharField(blank=True, max_length=32, null=True)),
                ('upload_name', models.CharField(blank=True, max_length=254, null=True)),
                ('upload_file', models.FileField(upload_to=uploader.models.user_directory_path)),
                ('upload_status', models.ForeignKey(db_column='upload_status', on_delete=django.db.models.deletion.DO_NOTHING, to='uploader.cofkcollectstatus')),
            ],
            options={
                'db_table': 'cofk_collect_upload',
            },
        ),
        migrations.CreateModel(
            name='CofkCollectToolSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_timestamp', models.DateTimeField()),
                ('session_code', models.TextField(blank=True, null=True, unique=True)),
                ('username', models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='uploader.cofkcollecttooluser')),
            ],
            options={
                'db_table': 'cofk_collect_tool_session',
            },
        ),
    ]
