# Generated by Django 4.0.6 on 2023-01-30 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_sync_old_schema'),
        ('location', '0003_cofkunionlocation_works'),
        ('work', '0005_alter_cofkunionqueryablework_work'),
        ('core', '0005_add_seq'),
        ('manifestation', '0003_sync_old_schema'),
        ('person', '0005_cofkunionperson_works'),
        ('uploader', '0002_sync_old_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkcollectimageofmanif',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.cofkcollectupload'),
        ),
        migrations.AlterField(
            model_name='cofkcollectinstitution',
            name='union_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.cofkunioninstitution'),
        ),
        migrations.AlterField(
            model_name='cofkcollectinstitutionresource',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.cofkcollectupload'),
        ),
        migrations.AlterField(
            model_name='cofkcollectlanguageofwork',
            name='iwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.cofkcollectwork'),
        ),
        migrations.AlterField(
            model_name='cofkcollectlanguageofwork',
            name='language_code',
            field=models.ForeignKey(db_column='language_code', on_delete=django.db.models.deletion.CASCADE, to='core.iso639languagecode'),
        ),
        migrations.AlterField(
            model_name='cofkcollectlocation',
            name='union_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.cofkunionlocation'),
        ),
        migrations.AlterField(
            model_name='cofkcollectlocationresource',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.cofkcollectupload'),
        ),
        migrations.AlterField(
            model_name='cofkcollectmanifestation',
            name='iwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.cofkcollectwork'),
        ),
        migrations.AlterField(
            model_name='cofkcollectmanifestation',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uploader.cofkcollectinstitution'),
        ),
        migrations.AlterField(
            model_name='cofkcollectmanifestation',
            name='union_manifestation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manifestation.cofkunionmanifestation'),
        ),
        migrations.AlterField(
            model_name='cofkcollectoccupationofperson',
            name='occupation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cofkunionrolecategory'),
        ),
        migrations.AlterField(
            model_name='cofkcollectoccupationofperson',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.cofkcollectupload'),
        ),
        migrations.AlterField(
            model_name='cofkcollectperson',
            name='union_iperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='union_collect_persons', to='person.cofkunionperson', to_field='iperson_id'),
        ),
        migrations.AlterField(
            model_name='cofkcollectpersonresource',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.cofkcollectupload'),
        ),
        migrations.AlterField(
            model_name='cofkcollectsubjectofwork',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cofkunionsubject'),
        ),
        migrations.AlterField(
            model_name='cofkcollecttoolsession',
            name='username',
            field=models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.SET_NULL, to='uploader.cofkcollecttooluser'),
        ),
        migrations.AlterField(
            model_name='cofkcollectupload',
            name='upload_status',
            field=models.ForeignKey(db_column='upload_status', null=True, on_delete=django.db.models.deletion.SET_NULL, to='uploader.cofkcollectstatus'),
        ),
        migrations.AlterField(
            model_name='cofkcollectwork',
            name='union_iwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='union_collect_works', to='work.cofkunionwork', to_field='iwork_id'),
        ),
        migrations.AlterField(
            model_name='cofkcollectwork',
            name='upload_status',
            field=models.ForeignKey(db_column='upload_status', null=True, on_delete=django.db.models.deletion.SET_NULL, to='uploader.cofkcollectstatus'),
        ),
        migrations.AlterField(
            model_name='cofkcollectwork',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collect_works', to='work.cofkunionwork'),
        ),
        migrations.AlterField(
            model_name='cofkcollectworksummary',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.cofkcollectupload'),
        ),
        migrations.AlterField(
            model_name='cofkcollectworksummary',
            name='work_id_in_tool',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='uploader.cofkcollectwork'),
        ),
    ]
