# Generated by Django 4.0.6 on 2022-09-01 13:00

import core.helper.model_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_set_default_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkunionauditliteral',
            name='change_timestamp',
            field=models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True),
        ),
        migrations.AlterField(
            model_name='cofkunionauditrelationship',
            name='change_timestamp',
            field=models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True),
        ),
        migrations.AlterField(
            model_name='cofkunionimage',
            name='change_timestamp',
            field=models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True),
        ),
        migrations.AlterField(
            model_name='cofkunionimage',
            name='creation_timestamp',
            field=models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True),
        ),
        migrations.AlterField(
            model_name='cofkunionpublication',
            name='change_timestamp',
            field=models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True),
        ),
        migrations.AlterField(
            model_name='cofkusersavedquery',
            name='creation_timestamp',
            field=models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True),
        ),
    ]
