# Generated by Django 4.0.6 on 2022-10-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_set_default_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iso639languagecode',
            name='code_639_3',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
