# Generated by Django 4.0.6 on 2022-12-20 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_sync_old_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkcollectlocation',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.cofkcollectupload'),
        ),
        migrations.AlterField(
            model_name='cofkcollectperson',
            name='iperson_id',
            field=models.IntegerField(),
        ),
    ]
