# Generated by Django 4.0.6 on 2022-11-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_set_default_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkunionimage',
            name='display_order',
            field=models.IntegerField(default=1),
        ),
    ]
