# Generated by Django 4.0.6 on 2023-04-28 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_alter_cofkcollectimageofmanif_upload_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cofkcollectplacementionedinwork',
            name='iwork_id',
        ),
        migrations.RemoveField(
            model_name='cofkcollectplacementionedinwork',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='cofkcollectsubjectofwork',
            name='iwork_id',
        ),
        migrations.AddField(
            model_name='cofkcollectplacementionedinwork',
            name='iwork',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uploader.cofkcollectwork'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cofkcollectplacementionedinwork',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uploader.cofkcollectlocation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cofkcollectsubjectofwork',
            name='iwork',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uploader.cofkcollectwork'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cofkcollectpersonmentionedinwork',
            name='_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
