# Generated by Django 4.0.6 on 2022-09-09 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_alter_cofkunionauditliteral_change_timestamp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CofkUnionPublication',
        ),
    ]
