# Generated by Django 4.0.6 on 2022-11-30 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_alter_cofkunionimage_display_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CofkUnionAuditLiteral',
        ),
        migrations.DeleteModel(
            name='CofkUnionAuditRelationship',
        ),
    ]
