# Generated by Django 4.0.6 on 2023-06-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_remove_cofkcollectplacementionedinwork_iwork_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkcollectperson',
            name='iperson_id',
            field=models.IntegerField(),
        ),
    ]
