# Generated by Django 4.0.6 on 2022-09-22 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_delete_cofkunionpublication'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='iso639languagecode',
            table='iso_639_language_codes',
        ),
    ]
