# Generated by Django 4.0.6 on 2022-09-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0005_alter_iso639languagecode_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkcollectstatus',
            name='status_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
