# Generated by Django 4.0.6 on 2023-07-24 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0005_remove_cofkcollectinstitutionresource_institution_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkcollectaddresseeofwork',
            name='iwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addressees', to='uploader.cofkcollectwork'),
        ),
        migrations.AlterField(
            model_name='cofkcollectauthorofwork',
            name='iperson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_of', to='uploader.cofkcollectperson'),
        ),
        migrations.AlterField(
            model_name='cofkcollectauthorofwork',
            name='iwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='uploader.cofkcollectwork'),
        ),
        migrations.AlterField(
            model_name='cofkcollectdestinationofwork',
            name='iwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='uploader.cofkcollectwork'),
        ),
        migrations.AlterField(
            model_name='cofkcollectlanguageofwork',
            name='iwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='uploader.cofkcollectwork'),
        ),
        migrations.AlterField(
            model_name='cofkcollectmanifestation',
            name='iwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifestations', to='uploader.cofkcollectwork'),
        ),
        migrations.AlterField(
            model_name='cofkcollectoriginofwork',
            name='iwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='uploader.cofkcollectwork'),
        ),
        migrations.AlterField(
            model_name='cofkcollectpersonmentionedinwork',
            name='iwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_mentioned', to='uploader.cofkcollectwork'),
        ),
        migrations.AlterField(
            model_name='cofkcollectplacementionedinwork',
            name='iwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places_mentioned', to='uploader.cofkcollectwork'),
        ),
        migrations.AlterField(
            model_name='cofkcollectsubjectofwork',
            name='iwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='uploader.cofkcollectwork'),
        ),
        migrations.AlterField(
            model_name='cofkcollectwork',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload', to='uploader.cofkcollectupload'),
        ),
        migrations.AlterField(
            model_name='cofkcollectworkresource',
            name='iwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='uploader.cofkcollectwork'),
        ),
    ]
