# Generated by Django 4.0.6 on 2022-09-23 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0006_alter_cofkcollectstatus_status_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cofklookupcatalogue',
            old_name='catalogue_id',
            new_name='catalogue',
        ),
    ]
