# Generated by Django 4.0.6 on 2023-08-04 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0006_alter_cofkcollectaddresseeofwork_iwork_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CofkCollectWorkSummary',
        ),
    ]
