# Generated by Django 4.0.6 on 2022-09-23 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0007_rename_catalogue_id_cofklookupcatalogue_catalogue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cofklookupcatalogue',
            old_name='catalogue',
            new_name='catalogue_id',
        ),
    ]
