# Generated by Django 4.0.6 on 2024-04-18 17:55

from django.db import migrations, models
import uploader.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0007_displayablecollectwork_delete_cofkcollectworksummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkcollectupload',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to=uploader.models.user_directory_path),
        ),
    ]
