# Generated by Django 4.0.6 on 2026-06-17 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0013_remove_cofkunionwork_work_date_std_idx_and_more'),
        ('uploader', '0009_cofkcollectupload_upload_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CofkCollectWorkCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iwork_id', models.IntegerField()),
                ('corrections', models.JSONField()),
                ('union_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collect_corrections', to='work.cofkunionwork', to_field='iwork_id')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='uploader.cofkcollectupload')),
                ('upload_status', models.ForeignKey(db_column='upload_status', null=True, on_delete=django.db.models.deletion.SET_NULL, to='uploader.cofkcollectstatus')),
            ],
            options={
                'db_table': 'cofk_collect_work_correction',
                'unique_together': {('upload', 'iwork_id')},
            },
        ),
    ]
