# Generated by Django 5.2.15 on 2026-09-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0010_cofkcollectworkcorrection'),
    ]

    operations = [
        migrations.AddField(
            model_name='cofkcollectperson',
            name='flourished_approx',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cofkcollectperson',
            name='flourished_inferred',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cofkcollectperson',
            name='flourished_uncertain',
            field=models.SmallIntegerField(default=0),
        ),
    ]
