<<<<<<< HEAD
# Generated by Django 4.0.6 on 2022-08-02 15:11

import core.helper.model_utils
=======
# Generated by Django 4.0.6 on 2022-07-12 11:13

>>>>>>> fb599c0 (Various)
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CofkUnionWork',
            fields=[
                ('work_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_of_work_as_marked', models.CharField(blank=True, max_length=250, null=True)),
                ('original_calendar', models.CharField(max_length=2)),
                ('date_of_work_std', models.CharField(blank=True, max_length=12, null=True)),
                ('date_of_work_std_gregorian', models.CharField(blank=True, max_length=12, null=True)),
                ('date_of_work_std_year', models.IntegerField(blank=True, null=True)),
                ('date_of_work_std_month', models.IntegerField(blank=True, null=True)),
                ('date_of_work_std_day', models.IntegerField(blank=True, null=True)),
                ('date_of_work2_std_year', models.IntegerField(blank=True, null=True)),
                ('date_of_work2_std_month', models.IntegerField(blank=True, null=True)),
                ('date_of_work2_std_day', models.IntegerField(blank=True, null=True)),
                ('date_of_work_std_is_range', models.SmallIntegerField()),
                ('date_of_work_inferred', models.SmallIntegerField()),
                ('date_of_work_uncertain', models.SmallIntegerField()),
                ('date_of_work_approx', models.SmallIntegerField()),
                ('authors_as_marked', models.TextField(blank=True, null=True)),
                ('addressees_as_marked', models.TextField(blank=True, null=True)),
                ('authors_inferred', models.SmallIntegerField()),
                ('authors_uncertain', models.SmallIntegerField()),
                ('addressees_inferred', models.SmallIntegerField()),
                ('addressees_uncertain', models.SmallIntegerField()),
                ('destination_as_marked', models.TextField(blank=True, null=True)),
                ('origin_as_marked', models.TextField(blank=True, null=True)),
                ('destination_inferred', models.SmallIntegerField()),
                ('destination_uncertain', models.SmallIntegerField()),
                ('origin_inferred', models.SmallIntegerField()),
                ('origin_uncertain', models.SmallIntegerField()),
                ('abstract', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('language_of_work', models.CharField(blank=True, max_length=255, null=True)),
                ('work_is_translation', models.SmallIntegerField()),
                ('incipit', models.TextField(blank=True, null=True)),
                ('explicit', models.TextField(blank=True, null=True)),
                ('ps', models.TextField(blank=True, null=True)),
                ('accession_code', models.CharField(blank=True, max_length=1000, null=True)),
                ('work_to_be_deleted', models.SmallIntegerField()),
                ('iwork_id', models.IntegerField()),
                ('editors_notes', models.TextField(blank=True, null=True)),
                ('edit_status', models.CharField(max_length=3)),
                ('relevant_to_cofk', models.CharField(max_length=3)),
                ('creation_timestamp', models.DateTimeField(blank=True, null=True)),
                ('creation_user', models.CharField(max_length=50)),
                ('change_timestamp', models.DateTimeField(blank=True, null=True)),
                ('change_user', models.CharField(max_length=50)),
                ('uuid', models.UUIDField(blank=True, null=True)),
                ('original_catalogue', models.ForeignKey(db_column='original_catalogue', on_delete=django.db.models.deletion.DO_NOTHING, to='uploader.cofklookupcatalogue')),
            ],
<<<<<<< HEAD
            options={
                'db_table': 'cofk_union_work',
            },
            bases=(models.Model, core.helper.model_utils.RecordTracker),
=======
>>>>>>> fb599c0 (Various)
        ),
        migrations.CreateModel(
            name='CofkUnionQueryableWork',
            fields=[
                ('iwork_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_of_work_std', models.DateField(blank=True, null=True)),
                ('date_of_work_std_year', models.IntegerField(blank=True, null=True)),
                ('date_of_work_std_month', models.IntegerField(blank=True, null=True)),
                ('date_of_work_std_day', models.IntegerField(blank=True, null=True)),
                ('date_of_work_as_marked', models.CharField(blank=True, max_length=250, null=True)),
                ('date_of_work_inferred', models.SmallIntegerField()),
                ('date_of_work_uncertain', models.SmallIntegerField()),
                ('date_of_work_approx', models.SmallIntegerField()),
                ('creators_searchable', models.TextField()),
                ('creators_for_display', models.TextField()),
                ('authors_as_marked', models.TextField(blank=True, null=True)),
                ('notes_on_authors', models.TextField(blank=True, null=True)),
                ('authors_inferred', models.SmallIntegerField()),
                ('authors_uncertain', models.SmallIntegerField()),
                ('addressees_searchable', models.TextField()),
                ('addressees_for_display', models.TextField()),
                ('addressees_as_marked', models.TextField(blank=True, null=True)),
                ('addressees_inferred', models.SmallIntegerField()),
                ('addressees_uncertain', models.SmallIntegerField()),
                ('places_from_searchable', models.TextField()),
                ('places_from_for_display', models.TextField()),
                ('origin_as_marked', models.TextField(blank=True, null=True)),
                ('origin_inferred', models.SmallIntegerField()),
                ('origin_uncertain', models.SmallIntegerField()),
                ('places_to_searchable', models.TextField()),
                ('places_to_for_display', models.TextField()),
                ('destination_as_marked', models.TextField(blank=True, null=True)),
                ('destination_inferred', models.SmallIntegerField()),
                ('destination_uncertain', models.SmallIntegerField()),
                ('manifestations_searchable', models.TextField()),
                ('manifestations_for_display', models.TextField()),
                ('abstract', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('people_mentioned', models.TextField(blank=True, null=True)),
                ('images', models.TextField(blank=True, null=True)),
                ('related_resources', models.TextField(blank=True, null=True)),
                ('language_of_work', models.CharField(blank=True, max_length=255, null=True)),
                ('work_is_translation', models.SmallIntegerField()),
                ('flags', models.TextField(blank=True, null=True)),
                ('edit_status', models.CharField(max_length=3)),
                ('general_notes', models.TextField(blank=True, null=True)),
                ('original_catalogue', models.CharField(max_length=100)),
                ('accession_code', models.CharField(blank=True, max_length=1000, null=True)),
                ('work_to_be_deleted', models.SmallIntegerField()),
                ('change_timestamp', models.DateTimeField(blank=True, null=True)),
                ('change_user', models.CharField(max_length=50)),
                ('drawer', models.CharField(blank=True, max_length=50, null=True)),
                ('editors_notes', models.TextField(blank=True, null=True)),
                ('manifestation_type', models.CharField(blank=True, max_length=50, null=True)),
                ('original_notes', models.TextField(blank=True, null=True)),
                ('relevant_to_cofk', models.CharField(max_length=1)),
                ('subjects', models.TextField(blank=True, null=True)),
                ('work', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='work.cofkunionwork')),
            ],
<<<<<<< HEAD
            options={
                'db_table': 'cofk_union_queryable_work',
            },
=======
>>>>>>> fb599c0 (Various)
        ),
        migrations.CreateModel(
            name='CofkCollectWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iwork_id', models.IntegerField()),
                ('date_of_work_as_marked', models.CharField(blank=True, max_length=250, null=True)),
                ('original_calendar', models.CharField(max_length=2)),
                ('date_of_work_std_year', models.IntegerField(blank=True, null=True)),
                ('date_of_work_std_month', models.IntegerField(blank=True, null=True)),
                ('date_of_work_std_day', models.IntegerField(blank=True, null=True)),
                ('date_of_work2_std_year', models.IntegerField(blank=True, null=True)),
                ('date_of_work2_std_month', models.IntegerField(blank=True, null=True)),
                ('date_of_work2_std_day', models.IntegerField(blank=True, null=True)),
                ('date_of_work_std_is_range', models.BooleanField(default=False, null=True)),
                ('date_of_work_inferred', models.BooleanField(default=False, null=True)),
                ('date_of_work_uncertain', models.BooleanField(default=False, null=True)),
                ('date_of_work_approx', models.BooleanField(default=False, null=True)),
                ('notes_on_date_of_work', models.TextField(blank=True, null=True)),
                ('authors_as_marked', models.TextField(blank=True, null=True)),
                ('authors_inferred', models.BooleanField(default=False, null=True)),
                ('authors_uncertain', models.BooleanField(default=False, null=True)),
                ('notes_on_authors', models.TextField(blank=True, null=True)),
                ('addressees_as_marked', models.TextField(blank=True, null=True)),
                ('addressees_inferred', models.BooleanField(default=False, null=True)),
                ('addressees_uncertain', models.BooleanField(default=False, null=True)),
                ('notes_on_addressees', models.TextField(blank=True, null=True)),
                ('destination_id', models.IntegerField(blank=True, null=True)),
                ('destination_as_marked', models.TextField(blank=True, null=True)),
                ('destination_inferred', models.BooleanField(default=False, null=True)),
                ('destination_uncertain', models.BooleanField(default=False, null=True)),
                ('origin_id', models.IntegerField(blank=True, null=True)),
                ('origin_as_marked', models.TextField(blank=True, null=True)),
                ('origin_inferred', models.BooleanField(default=False, null=True)),
                ('origin_uncertain', models.BooleanField(default=False, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('language_of_work', models.CharField(blank=True, max_length=255, null=True)),
                ('incipit', models.TextField(blank=True, null=True)),
                ('excipit', models.TextField(blank=True, null=True)),
                ('accession_code', models.CharField(blank=True, max_length=250, null=True)),
                ('notes_on_letter', models.TextField(blank=True, null=True)),
                ('notes_on_people_mentioned', models.TextField(blank=True, null=True)),
                ('editors_notes', models.TextField(blank=True, null=True)),
                ('_id', models.CharField(max_length=32)),
                ('date_of_work2_approx', models.BooleanField(default=False, null=True)),
                ('date_of_work2_inferred', models.BooleanField(default=False, null=True)),
                ('date_of_work2_uncertain', models.BooleanField(default=False, null=True)),
                ('mentioned_as_marked', models.TextField(blank=True, null=True)),
                ('mentioned_inferred', models.SmallIntegerField()),
                ('mentioned_uncertain', models.SmallIntegerField()),
                ('notes_on_destination', models.TextField(blank=True, null=True)),
                ('notes_on_origin', models.TextField(blank=True, null=True)),
                ('notes_on_place_mentioned', models.TextField(blank=True, null=True)),
                ('place_mentioned_as_marked', models.TextField(blank=True, null=True)),
                ('place_mentioned_inferred', models.SmallIntegerField()),
                ('place_mentioned_uncertain', models.SmallIntegerField()),
                ('upload_name', models.CharField(blank=True, max_length=254, null=True)),
                ('explicit', models.TextField(blank=True, null=True)),
                ('union_iwork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='union_collect_works', to='work.cofkunionwork')),
<<<<<<< HEAD
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='uploader.cofkcollectupload')),
=======
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.cofkcollectupload')),
>>>>>>> fb599c0 (Various)
                ('upload_status', models.ForeignKey(db_column='upload_status', on_delete=django.db.models.deletion.DO_NOTHING, to='uploader.cofkcollectstatus')),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='collect_works', to='work.cofkunionwork')),
            ],
            options={
                'db_table': 'cofk_collect_work',
                'unique_together': {('upload', 'iwork_id')},
            },
        ),
        migrations.CreateModel(
            name='CofkCollectWorkSummary',
            fields=[
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='work.cofkcollectwork')),
                ('work_id_in_tool', models.IntegerField()),
                ('source_of_data', models.CharField(blank=True, max_length=250, null=True)),
                ('notes_on_letter', models.TextField(blank=True, null=True)),
                ('date_of_work', models.CharField(blank=True, max_length=32, null=True)),
                ('date_of_work_as_marked', models.CharField(blank=True, max_length=250, null=True)),
                ('original_calendar', models.CharField(blank=True, max_length=30, null=True)),
                ('date_of_work_is_range', models.CharField(blank=True, max_length=30, null=True)),
                ('date_of_work_inferred', models.CharField(blank=True, max_length=30, null=True)),
                ('date_of_work_uncertain', models.CharField(blank=True, max_length=30, null=True)),
                ('date_of_work_approx', models.CharField(blank=True, max_length=30, null=True)),
                ('notes_on_date_of_work', models.TextField(blank=True, null=True)),
                ('authors', models.TextField(blank=True, null=True)),
                ('authors_as_marked', models.TextField(blank=True, null=True)),
                ('authors_inferred', models.CharField(blank=True, max_length=30, null=True)),
                ('authors_uncertain', models.CharField(blank=True, max_length=30, null=True)),
                ('notes_on_authors', models.TextField(blank=True, null=True)),
                ('addressees', models.TextField(blank=True, null=True)),
                ('addressees_as_marked', models.TextField(blank=True, null=True)),
                ('addressees_inferred', models.CharField(blank=True, max_length=30, null=True)),
                ('addressees_uncertain', models.CharField(blank=True, max_length=30, null=True)),
                ('notes_on_addressees', models.TextField(blank=True, null=True)),
                ('destination', models.TextField(blank=True, null=True)),
                ('destination_as_marked', models.TextField(blank=True, null=True)),
                ('destination_inferred', models.CharField(blank=True, max_length=30, null=True)),
                ('destination_uncertain', models.CharField(blank=True, max_length=30, null=True)),
                ('origin', models.TextField(blank=True, null=True)),
                ('origin_as_marked', models.TextField(blank=True, null=True)),
                ('origin_inferred', models.CharField(blank=True, max_length=30, null=True)),
                ('origin_uncertain', models.CharField(blank=True, max_length=30, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('languages_of_work', models.TextField(blank=True, null=True)),
                ('subjects_of_work', models.TextField(blank=True, null=True)),
                ('incipit', models.TextField(blank=True, null=True)),
                ('excipit', models.TextField(blank=True, null=True)),
                ('people_mentioned', models.TextField(blank=True, null=True)),
                ('notes_on_people_mentioned', models.TextField(blank=True, null=True)),
                ('places_mentioned', models.TextField(blank=True, null=True)),
                ('manifestations', models.TextField(blank=True, null=True)),
                ('related_resources', models.TextField(blank=True, null=True)),
                ('editors_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cofk_collect_work_summary',
                'unique_together': {('upload', 'work_id_in_tool')},
            },
        ),
        migrations.CreateModel(
            name='CofkCollectWorkResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.IntegerField()),
                ('iwork_id', models.IntegerField()),
                ('resource_name', models.TextField()),
                ('resource_details', models.TextField()),
                ('resource_url', models.TextField()),
                ('_id', models.CharField(blank=True, max_length=32, null=True)),
<<<<<<< HEAD
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='uploader.cofkcollectupload')),
=======
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.cofkcollectupload')),
>>>>>>> fb599c0 (Various)
            ],
            options={
                'db_table': 'cofk_collect_work_resource',
                'unique_together': {('upload', 'iwork_id', 'resource_id')},
            },
        ),
        migrations.CreateModel(
            name='CofkCollectSubjectOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_of_work_id', models.IntegerField()),
                ('iwork_id', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='uploader.cofkunionsubject')),
<<<<<<< HEAD
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='uploader.cofkcollectupload')),
=======
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.cofkcollectupload')),
>>>>>>> fb599c0 (Various)
            ],
            options={
                'db_table': 'cofk_collect_subject_of_work',
                'unique_together': {('upload', 'iwork_id', 'subject_of_work_id')},
            },
        ),
        migrations.CreateModel(
            name='CofkCollectPlaceMentionedInWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mention_id', models.IntegerField()),
                ('location_id', models.IntegerField()),
                ('iwork_id', models.IntegerField()),
                ('notes_on_place_mentioned', models.TextField(blank=True, null=True)),
                ('_id', models.CharField(blank=True, max_length=32, null=True)),
<<<<<<< HEAD
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='uploader.cofkcollectupload')),
=======
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.cofkcollectupload')),
>>>>>>> fb599c0 (Various)
            ],
            options={
                'db_table': 'cofk_collect_place_mentioned_in_work',
                'unique_together': {('upload', 'iwork_id', 'mention_id')},
            },
        ),
        migrations.CreateModel(
            name='CofkCollectPersonMentionedInWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mention_id', models.IntegerField()),
                ('iperson_id', models.IntegerField()),
                ('iwork_id', models.IntegerField()),
                ('notes_on_person_mentioned', models.TextField(blank=True, null=True)),
                ('_id', models.CharField(max_length=32)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.cofkcollectupload')),
            ],
            options={
                'db_table': 'cofk_collect_person_mentioned_in_work',
                'unique_together': {('upload', 'iwork_id', 'mention_id')},
            },
        ),
        migrations.CreateModel(
            name='CofkCollectOriginOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.IntegerField()),
                ('location_id', models.IntegerField()),
                ('iwork_id', models.IntegerField()),
                ('notes_on_origin', models.TextField(blank=True, null=True)),
                ('_id', models.CharField(blank=True, max_length=32, null=True)),
<<<<<<< HEAD
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='uploader.cofkcollectupload')),
=======
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='uploader.cofkcollectupload')),
>>>>>>> fb599c0 (Various)
            ],
            options={
                'db_table': 'cofk_collect_origin_of_work',
                'unique_together': {('upload', 'iwork_id', 'origin_id')},
            },
        ),
        migrations.CreateModel(
            name='CofkCollectLanguageOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_of_work_id', models.IntegerField()),
                ('iwork_id', models.IntegerField()),
                ('_id', models.CharField(blank=True, max_length=32, null=True)),
                ('language_code', models.ForeignKey(db_column='language_code', on_delete=django.db.models.deletion.DO_NOTHING, to='uploader.iso639languagecode')),
<<<<<<< HEAD
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='uploader.cofkcollectupload')),
=======
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.cofkcollectupload')),
>>>>>>> fb599c0 (Various)
            ],
            options={
                'db_table': 'cofk_collect_language_of_work',
                'unique_together': {('upload', 'iwork_id', 'language_of_work_id')},
            },
        ),
        migrations.CreateModel(
            name='CofkCollectDestinationOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_id', models.IntegerField()),
                ('location_id', models.IntegerField()),
                ('iwork_id', models.IntegerField()),
                ('notes_on_destination', models.TextField(blank=True, null=True)),
                ('_id', models.CharField(blank=True, max_length=32, null=True)),
<<<<<<< HEAD
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='uploader.cofkcollectupload')),
=======
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.cofkcollectupload')),
>>>>>>> fb599c0 (Various)
            ],
            options={
                'db_table': 'cofk_collect_destination_of_work',
                'unique_together': {('upload', 'iwork_id', 'destination_id')},
            },
        ),
        migrations.CreateModel(
            name='CofkCollectAuthorOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.IntegerField()),
                ('iperson_id', models.IntegerField()),
                ('iwork_id', models.IntegerField()),
                ('notes_on_author', models.TextField(blank=True, null=True)),
                ('_id', models.CharField(blank=True, max_length=32, null=True)),
<<<<<<< HEAD
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='uploader.cofkcollectupload')),
=======
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.cofkcollectupload')),
>>>>>>> fb599c0 (Various)
            ],
            options={
                'db_table': 'cofk_collect_author_of_work',
                'unique_together': {('upload', 'iwork_id', 'author_id')},
            },
        ),
        migrations.CreateModel(
            name='CofkCollectAddresseeOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressee_id', models.IntegerField()),
                ('iperson_id', models.IntegerField()),
                ('iwork_id', models.IntegerField()),
                ('notes_on_addressee', models.TextField(blank=True, null=True)),
                ('_id', models.CharField(blank=True, max_length=32, null=True)),
<<<<<<< HEAD
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='uploader.cofkcollectupload')),
=======
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='uploader.cofkcollectupload')),
>>>>>>> fb599c0 (Various)
            ],
            options={
                'db_table': 'cofk_collect_addressee_of_work',
                'unique_together': {('upload', 'iwork_id', 'addressee_id')},
            },
        ),
        migrations.CreateModel(
            name='CofkUnionLanguageOfWork',
            fields=[
                ('work', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='work.cofkunionwork')),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
                ('language_code', models.ForeignKey(db_column='language_code', on_delete=django.db.models.deletion.DO_NOTHING, to='uploader.iso639languagecode')),
            ],
            options={
                'db_table': 'cofk_union_language_of_work',
                'unique_together': {('work', 'language_code')},
            },
        ),
    ]
