# Generated by Django 4.0.6 on 2022-09-30 14:47

import core.helper.model_utils
from django.db import migrations, models
import django.db.models.deletion
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_set_default_values'),
        ('work', '0002_create_seq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkunionwork',
            name='addressees_inferred',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cofkunionwork',
            name='addressees_uncertain',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cofkunionwork',
            name='authors_inferred',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cofkunionwork',
            name='authors_uncertain',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cofkunionwork',
            name='date_of_work_approx',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cofkunionwork',
            name='date_of_work_inferred',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cofkunionwork',
            name='date_of_work_std',
            field=models.CharField(blank=True, default='9999-12-31', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cofkunionwork',
            name='date_of_work_std_gregorian',
            field=models.CharField(blank=True, default='9999-12-31', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cofkunionwork',
            name='date_of_work_std_is_range',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cofkunionwork',
            name='date_of_work_uncertain',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cofkunionwork',
            name='destination_inferred',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cofkunionwork',
            name='destination_uncertain',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cofkunionwork',
            name='edit_status',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='cofkunionwork',
            name='iwork_id',
            field=models.IntegerField(default=functools.partial(core.helper.model_utils.next_seq_safe, *('cofk_union_person_iwork_id_seq',), **{}), unique=True),
        ),
        migrations.AlterField(
            model_name='cofkunionwork',
            name='origin_inferred',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cofkunionwork',
            name='origin_uncertain',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cofkunionwork',
            name='original_calendar',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='cofkunionwork',
            name='original_catalogue',
            field=models.ForeignKey(blank=True, db_column='original_catalogue', default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='uploader.cofklookupcatalogue'),
        ),
        migrations.AlterField(
            model_name='cofkunionwork',
            name='relevant_to_cofk',
            field=models.CharField(default='Y', max_length=3),
        ),
        migrations.AlterField(
            model_name='cofkunionwork',
            name='uuid',
            field=models.UUIDField(blank=True, default=core.helper.model_utils.default_uuid, null=True),
        ),
        migrations.AlterField(
            model_name='cofkunionwork',
            name='work_is_translation',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cofkunionwork',
            name='work_to_be_deleted',
            field=models.SmallIntegerField(default=0),
        ),
    ]
