# Generated by Django 4.0.6 on 2022-09-22 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0010_alter_cofkcollectperson_upload'),
        ('uploader', '0005_alter_iso639languagecode_table'),
        ('location', '0003_alter_cofkcollectlocation_upload'),
        ('work', '0002_alter_cofkunionqueryablework_change_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cofkcollectaddresseeofwork',
            name='iperson_id',
        ),
        migrations.RemoveField(
            model_name='cofkcollectaddresseeofwork',
            name='iwork_id',
        ),
        migrations.RemoveField(
            model_name='cofkcollectauthorofwork',
            name='iperson_id',
        ),
        migrations.RemoveField(
            model_name='cofkcollectauthorofwork',
            name='iwork_id',
        ),
        migrations.RemoveField(
            model_name='cofkcollectdestinationofwork',
            name='iwork_id',
        ),
        migrations.RemoveField(
            model_name='cofkcollectdestinationofwork',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='cofkcollectlanguageofwork',
            name='iwork_id',
        ),
        migrations.RemoveField(
            model_name='cofkcollectoriginofwork',
            name='iwork_id',
        ),
        migrations.RemoveField(
            model_name='cofkcollectoriginofwork',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='cofkcollectpersonmentionedinwork',
            name='iperson_id',
        ),
        migrations.RemoveField(
            model_name='cofkcollectpersonmentionedinwork',
            name='iwork_id',
        ),
        migrations.RemoveField(
            model_name='cofkcollectwork',
            name='destination_id',
        ),
        migrations.RemoveField(
            model_name='cofkcollectwork',
            name='origin_id',
        ),
        migrations.RemoveField(
            model_name='cofkcollectworkresource',
            name='iwork_id',
        ),
        migrations.AddField(
            model_name='cofkcollectaddresseeofwork',
            name='iperson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.cofkcollectperson'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cofkcollectaddresseeofwork',
            name='iwork',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='work.cofkcollectwork'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cofkcollectauthorofwork',
            name='iperson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.cofkcollectperson'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cofkcollectauthorofwork',
            name='iwork',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='work.cofkcollectwork'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cofkcollectdestinationofwork',
            name='iwork',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='work.cofkcollectwork'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cofkcollectdestinationofwork',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='location.cofkcollectlocation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cofkcollectlanguageofwork',
            name='iwork',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='work.cofkcollectwork'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cofkcollectoriginofwork',
            name='iwork',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='work.cofkcollectwork'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cofkcollectoriginofwork',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='location.cofkcollectlocation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cofkcollectpersonmentionedinwork',
            name='iperson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.cofkcollectperson'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cofkcollectpersonmentionedinwork',
            name='iwork',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='work.cofkcollectwork'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cofkcollectwork',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work.cofkcollectdestinationofwork'),
        ),
        migrations.AddField(
            model_name='cofkcollectwork',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work.cofkcollectoriginofwork'),
        ),
        migrations.AddField(
            model_name='cofkcollectworkresource',
            name='iwork',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='work.cofkcollectwork'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cofkcollectaddresseeofwork',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.cofkcollectupload'),
        ),
        migrations.AlterField(
            model_name='cofkcollectauthorofwork',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.cofkcollectupload'),
        ),
        migrations.AlterField(
            model_name='cofkcollectdestinationofwork',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.cofkcollectupload'),
        ),
        migrations.AlterField(
            model_name='cofkcollectlanguageofwork',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.cofkcollectupload'),
        ),
        migrations.AlterField(
            model_name='cofkcollectoriginofwork',
            name='upload',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='uploader.cofkcollectupload'),
        ),
        migrations.AlterField(
            model_name='cofkcollectplacementionedinwork',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.cofkcollectupload'),
        ),
        migrations.AlterField(
            model_name='cofkcollectsubjectofwork',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.cofkcollectupload'),
        ),
        migrations.AlterField(
            model_name='cofkcollectwork',
            name='_id',
            field=models.CharField(blank=True, db_column='_id', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cofkcollectwork',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.cofkcollectupload'),
        ),
        migrations.AlterField(
            model_name='cofkcollectworkresource',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.cofkcollectupload'),
        ),
    ]
