# Generated by Django 4.0.6 on 2022-11-03 15:20

import core.helper.model_utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_set_default_values'),
        ('work', '0002_create_seq'),
    ]

    operations = [
        migrations.CreateModel(
            name='CofkWorkSubjectMap',
            fields=[
                ('recref_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_date', models.DateField(null=True)),
                ('to_date', models.DateField(null=True)),
                ('relationship_type', models.CharField(max_length=100)),
                ('creation_timestamp', models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True)),
                ('creation_user', models.CharField(max_length=50)),
                ('change_timestamp', models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True)),
                ('change_user', models.CharField(max_length=50)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.cofkunionsubject')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.cofkunionwork')),
            ],
            options={
                'db_table': 'cofk_work_subject_map',
                'abstract': False,
            },
            bases=(models.Model, core.helper.model_utils.RecordTracker),
        ),
    ]
