# Generated by Django 4.0.6 on 2022-09-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_remove_cofkcollectaddresseeofwork_iperson_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkcollectwork',
            name='addressees_inferred',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cofkcollectwork',
            name='addressees_uncertain',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cofkcollectwork',
            name='authors_inferred',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cofkcollectwork',
            name='authors_uncertain',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cofkcollectwork',
            name='date_of_work2_approx',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cofkcollectwork',
            name='date_of_work2_inferred',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cofkcollectwork',
            name='date_of_work2_uncertain',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cofkcollectwork',
            name='date_of_work_approx',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cofkcollectwork',
            name='date_of_work_inferred',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cofkcollectwork',
            name='date_of_work_std_is_range',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cofkcollectwork',
            name='date_of_work_uncertain',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cofkcollectwork',
            name='destination_inferred',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cofkcollectwork',
            name='destination_uncertain',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cofkcollectwork',
            name='origin_inferred',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cofkcollectwork',
            name='origin_uncertain',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
