# Generated by Django 4.0.6 on 2022-12-19 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_sync_old_schema'),
        ('work', '0003_sync_old_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkunionwork',
            name='original_catalogue',
            field=models.ForeignKey(blank=True, db_column='original_catalogue', default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='uploader.cofklookupcatalogue', to_field='catalogue_code'),
        ),
    ]
