# Generated by Django 4.0.6 on 2022-11-28 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_alter_cofkunionimage_display_order'),
        ('work', '0004_alter_cofkunionwork_iwork_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cofkcollectoriginofwork',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cofkcollectoriginofwork',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.cofkcollectupload'),
        ),
        migrations.AlterField(
            model_name='cofkcollectwork',
            name='original_calendar',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='cofkcollectoriginofwork',
            unique_together={('upload', 'iwork', 'origin_id')},
        ),
    ]
