# Generated by Django 4.0.6 on 2022-09-23 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0008_rename_catalogue_cofklookupcatalogue_catalogue_id'),
        ('work', '0004_alter_cofkcollectwork_addressees_inferred_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkunionwork',
            name='original_catalogue',
            field=models.ForeignKey(blank=True, db_column='original_catalogue', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='uploader.cofklookupcatalogue'),
        ),
    ]
