# Generated by Django 4.0.6 on 2022-11-01 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('work', '0004_alter_cofkunionlanguageofwork_language_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CofkWorkComment',
            new_name='CofkWorkCommentMap',
        ),
    ]
