# Generated by Django 4.0.6 on 2023-01-30 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_add_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkunionqueryablework',
            name='work',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='queryable', to='work.cofkunionwork'),
        ),
    ]
