# Generated by Django 4.0.6 on 2022-10-06 13:30

import core.helper.model_utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_alter_cofkworkpersonmap_work_cofkworkcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CofkWorkWorkMap',
            fields=[
                ('recref_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_date', models.DateField(null=True)),
                ('to_date', models.DateField(null=True)),
                ('relationship_type', models.CharField(max_length=100)),
                ('creation_timestamp', models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True)),
                ('creation_user', models.CharField(max_length=50)),
                ('change_timestamp', models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True)),
                ('change_user', models.CharField(max_length=50)),
                ('work_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_from_set', to='work.cofkunionwork')),
                ('work_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_to_set', to='work.cofkunionwork')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, core.helper.model_utils.RecordTracker),
        ),
    ]
