# Generated by Django 4.0.6 on 2022-10-06 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_cofkworkworkmap'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cofkworkcomment',
            table='cofk_work_comment_map',
        ),
        migrations.AlterModelTable(
            name='cofkworkworkmap',
            table='cofk_work_work_map',
        ),
    ]
