# Generated by Django 4.0.6 on 2023-05-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_delete_cofkunionqueryablework'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cofkworkcommentmap',
            index=models.Index(fields=['work', 'relationship_type'], name='cofk_work_c_work_id_6283a1_idx'),
        ),
        migrations.AddIndex(
            model_name='cofkworklocationmap',
            index=models.Index(fields=['work', 'relationship_type'], name='cofk_work_l_work_id_e9191a_idx'),
        ),
        migrations.AddIndex(
            model_name='cofkworkpersonmap',
            index=models.Index(fields=['work', 'relationship_type'], name='cofk_work_p_work_id_42dd8f_idx'),
        ),
        migrations.AddIndex(
            model_name='cofkworkresourcemap',
            index=models.Index(fields=['work', 'relationship_type'], name='cofk_work_r_work_id_11c372_idx'),
        ),
        migrations.AddIndex(
            model_name='cofkworksubjectmap',
            index=models.Index(fields=['work', 'relationship_type'], name='cofk_work_s_work_id_4b7303_idx'),
        ),
        migrations.AddIndex(
            model_name='cofkworkworkmap',
            index=models.Index(fields=['work_from', 'relationship_type'], name='cofk_work_w_work_fr_001849_idx'),
        ),
        migrations.AddIndex(
            model_name='cofkworkworkmap',
            index=models.Index(fields=['work_to', 'relationship_type'], name='cofk_work_w_work_to_a241c9_idx'),
        ),
    ]
