# Generated by Django 4.0.6 on 2023-06-14 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_cofkworkcommentmap_cofk_work_c_work_id_6283a1_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayableWork',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('work.cofkunionwork',),
        ),
        migrations.AlterModelOptions(
            name='cofkunionwork',
            options={'permissions': [('export_file', 'Export csv/excel from search results')]},
        ),
    ]
