# Generated by Django 4.0.6 on 2024-09-24 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0011_cofkunionwork_cofk_union__iwork_i_98a3a4_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cofkunionwork',
            options={'permissions': [('export_file', 'Export csv/excel from search results'), ('tombstone', 'Allow use tombstone feature to find similar records')]},
        ),
    ]
