# Generated by Django 4.0.6 on 2025-11-18 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_add_work_search_indexes'),
        ('work', '0011_alter_cofkunionwork_iwork_id'),
    ]

    operations = [
    ]
