# Generated by Django 4.0.6 on 2026-02-25 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0012_merge_20251118_1048'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cofkunionwork',
            name='work_date_std_idx',
        ),
        migrations.RemoveIndex(
            model_name='cofkunionwork',
            name='work_date_iwork_idx',
        ),
        migrations.RemoveIndex(
            model_name='cofkunionwork',
            name='work_change_ts_idx',
        ),
    ]
