# Generated by Django 5.2.15 on 2026-07-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0013_remove_cofkunionwork_work_date_std_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkunionwork',
            name='change_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofkunionwork',
            name='creation_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofkworkcommentmap',
            name='change_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofkworkcommentmap',
            name='creation_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofkworklocationmap',
            name='change_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofkworklocationmap',
            name='creation_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofkworkpersonmap',
            name='change_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofkworkpersonmap',
            name='creation_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofkworkresourcemap',
            name='change_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofkworkresourcemap',
            name='creation_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofkworksubjectmap',
            name='change_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofkworksubjectmap',
            name='creation_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofkworkworkmap',
            name='change_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofkworkworkmap',
            name='creation_user',
            field=models.CharField(max_length=254),
        ),
    ]
