# Generated by Django 4.0.6 on 2022-10-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cofkuserroles',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cofkuserroles',
            name='role',
        ),
        migrations.RemoveField(
            model_name='cofkuserroles',
            name='username',
        ),
        migrations.AddField(
            model_name='cofkuser',
            name='login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CofkRoles',
        ),
        migrations.DeleteModel(
            name='CofkUserRoles',
        ),
    ]
