# Generated by Django 4.0.5 on 2022-06-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cofkuser',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='cofkuser',
            name='login_time',
        ),
        migrations.AlterField(
            model_name='cofkuser',
            name='failed_logins',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cofkuser',
            name='prev_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
