# Generated by Django 4.0.5 on 2022-06-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cofkuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
