# Generated by Django 5.2.15 on 2026-07-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_cofkuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkuser',
            name='username',
            field=models.CharField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
