from django.db import migrations

from cllib_django import migrations_utils


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('uploader', '0001_initial'),
        ('core', '0003_basic_db_settings'),
    ]
    operations = [
        migrations_utils.create_operation_default_value('cofk_collect_upload', 'upload_status', '1'),
        migrations_utils.create_operation_default_value('cofk_collect_upload', 'upload_timestamp', 'now()'),
        migrations_utils.create_operation_default_value('cofk_collect_upload', 'total_works', '0'),
        migrations_utils.create_operation_default_value('cofk_collect_upload', 'works_accepted', '0'),
        migrations_utils.create_operation_default_value('cofk_collect_upload', 'works_rejected', '0'),
        migrations_utils.create_operation_default_value('cofk_collect_upload', 'uploader_email', "''"),
        migrations_utils.create_operation_default_value('cofk_collect_tool_session', 'session_timestamp', 'now()'),
        migrations_utils.create_operation_default_value('cofk_collect_status', 'editable', '1'),
        migrations_utils.create_operation_default_value('cofk_collect_institution', 'institution_name', "''"),
        migrations_utils.create_operation_default_value('cofk_collect_institution', 'institution_city', "''"),
        migrations_utils.create_operation_default_value('cofk_collect_institution', 'institution_country', "''"),
        migrations_utils.create_operation_default_value('cofk_collect_institution_resource', 'resource_name', "''"),
        migrations_utils.create_operation_default_value('cofk_collect_institution_resource', 'resource_details', "''"),
        migrations_utils.create_operation_default_value('cofk_collect_institution_resource', 'resource_url', "''"),
        migrations_utils.create_operation_default_value('cofk_collect_location', 'location_name', "''"),
        migrations_utils.create_operation_default_value('cofk_collect_location', 'element_1_eg_room', "''"),
        migrations_utils.create_operation_default_value('cofk_collect_location', 'element_2_eg_building', "''"),
        migrations_utils.create_operation_default_value('cofk_collect_location', 'element_3_eg_parish', "''"),
        migrations_utils.create_operation_default_value('cofk_collect_location', 'element_4_eg_city', "''"),
        migrations_utils.create_operation_default_value('cofk_collect_location', 'element_5_eg_county', "''"),
        migrations_utils.create_operation_default_value('cofk_collect_location', 'element_6_eg_country', "''"),
        migrations_utils.create_operation_default_value('cofk_collect_location', 'element_7_eg_empire', "''"),
        migrations_utils.create_operation_default_value('cofk_collect_location_resource', 'resource_name', "''"),
        migrations_utils.create_operation_default_value('cofk_collect_location_resource', 'resource_details', "''"),
        migrations_utils.create_operation_default_value('cofk_collect_location_resource', 'resource_url', "''"),

        migrations_utils.create_operation_default_value('cofk_collect_location', 'location_name', "''"),
        migrations_utils.create_operation_default_value('cofk_collect_location', 'element_1_eg_room', "''"),
        migrations_utils.create_operation_default_value('cofk_collect_location', 'element_2_eg_building', "''"),
        migrations_utils.create_operation_default_value('cofk_collect_location', 'element_3_eg_parish', "''"),
        migrations_utils.create_operation_default_value('cofk_collect_location', 'element_4_eg_city', "''"),
        migrations_utils.create_operation_default_value('cofk_collect_location', 'element_5_eg_county', "''"),
        migrations_utils.create_operation_default_value('cofk_collect_location', 'element_6_eg_country', "''"),
        migrations_utils.create_operation_default_value('cofk_collect_location', 'element_7_eg_empire', "''"),
        migrations_utils.create_operation_default_value('cofk_collect_location_resource', 'resource_name', "''"),
        migrations_utils.create_operation_default_value('cofk_collect_location_resource', 'resource_details', "''"),
        migrations_utils.create_operation_default_value('cofk_collect_location_resource', 'resource_url', "''"),

        migrations_utils.create_operation_default_value('cofk_collect_manifestation', 'manifestation_type', "''"),

        migrations_utils.create_operation_default_value('cofk_collect_person_resource', 'resource_name', "''"),
        migrations_utils.create_operation_default_value('cofk_collect_person_resource', 'resource_details', "''"),
        migrations_utils.create_operation_default_value('cofk_collect_person_resource', 'resource_url', "''"),
        migrations_utils.create_operation_default_value('cofk_collect_person', 'gender', "''"),
        migrations_utils.create_operation_default_value('cofk_collect_person', 'is_organisation', "''"),
        migrations_utils.create_operation_default_value('cofk_collect_person', 'date_of_birth_is_range', '0'),
        migrations_utils.create_operation_default_value('cofk_collect_person', 'date_of_birth_inferred', '0'),
        migrations_utils.create_operation_default_value('cofk_collect_person', 'date_of_birth_uncertain', '0'),
        migrations_utils.create_operation_default_value('cofk_collect_person', 'date_of_birth_approx', '0'),
        migrations_utils.create_operation_default_value('cofk_collect_person', 'date_of_death_is_range', '0'),
        migrations_utils.create_operation_default_value('cofk_collect_person', 'date_of_death_inferred', '0'),
        migrations_utils.create_operation_default_value('cofk_collect_person', 'date_of_death_uncertain', '0'),
        migrations_utils.create_operation_default_value('cofk_collect_person', 'date_of_death_approx', '0'),
        migrations_utils.create_operation_default_value('cofk_collect_person', 'flourished_is_range', '0'),

        migrations_utils.create_operation_default_value('cofk_collect_work', 'original_calendar', "''"),
        migrations_utils.create_operation_default_value('cofk_collect_work', 'date_of_work_std_is_range', '0'),
        migrations_utils.create_operation_default_value('cofk_collect_work', 'date_of_work_inferred', '0'),
        migrations_utils.create_operation_default_value('cofk_collect_work', 'date_of_work_uncertain', '0'),
        migrations_utils.create_operation_default_value('cofk_collect_work', 'date_of_work_approx', '0'),
        migrations_utils.create_operation_default_value('cofk_collect_work', 'authors_inferred', '0'),
        migrations_utils.create_operation_default_value('cofk_collect_work', 'authors_uncertain', '0'),
        migrations_utils.create_operation_default_value('cofk_collect_work', 'addressees_inferred', '0'),
        migrations_utils.create_operation_default_value('cofk_collect_work', 'addressees_uncertain', '0'),
        migrations_utils.create_operation_default_value('cofk_collect_work', 'destination_inferred', '0'),
        migrations_utils.create_operation_default_value('cofk_collect_work', 'destination_uncertain', '0'),
        migrations_utils.create_operation_default_value('cofk_collect_work', 'origin_inferred', '0'),
        migrations_utils.create_operation_default_value('cofk_collect_work', 'origin_uncertain', '0'),
        migrations_utils.create_operation_default_value('cofk_collect_work', 'date_of_work2_approx', '0'),
        migrations_utils.create_operation_default_value('cofk_collect_work', 'date_of_work2_inferred', '0'),
        migrations_utils.create_operation_default_value('cofk_collect_work', 'date_of_work2_uncertain', '0'),
        migrations_utils.create_operation_default_value('cofk_collect_work', 'mentioned_inferred', '0'),
        migrations_utils.create_operation_default_value('cofk_collect_work', 'mentioned_uncertain', '0'),
        migrations_utils.create_operation_default_value('cofk_collect_work', 'place_mentioned_inferred', '0'),
        migrations_utils.create_operation_default_value('cofk_collect_work', 'place_mentioned_uncertain', '0'),
        migrations_utils.create_operation_default_value('cofk_collect_work', 'upload_status', '1'),
        migrations_utils.create_operation_default_value('cofk_collect_work_resource', 'resource_name', "''"),
        migrations_utils.create_operation_default_value('cofk_collect_work_resource', 'resource_details', "''"),
        migrations_utils.create_operation_default_value('cofk_collect_work_resource', 'resource_url', "''"),

    ]
