# Generated by Django 4.0.6 on 2022-09-30 11:28

import core.helper.model_utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0002_initial'),
        ('work', '0001_initial'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CofkUnionManifestation',
            fields=[
                ('manifestation_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('manifestation_type', models.CharField(max_length=3)),
                ('id_number_or_shelfmark', models.CharField(blank=True, max_length=500, null=True)),
                ('printed_edition_details', models.TextField(blank=True, null=True)),
                ('paper_size', models.CharField(blank=True, max_length=500, null=True)),
                ('paper_type_or_watermark', models.CharField(blank=True, max_length=500, null=True)),
                ('number_of_pages_of_document', models.IntegerField(blank=True, null=True)),
                ('number_of_pages_of_text', models.IntegerField(blank=True, null=True)),
                ('seal', models.CharField(blank=True, max_length=500, null=True)),
                ('postage_marks', models.CharField(blank=True, max_length=500, null=True)),
                ('endorsements', models.TextField(blank=True, null=True)),
                ('non_letter_enclosures', models.TextField(blank=True, null=True)),
                ('manifestation_creation_calendar', models.CharField(max_length=2)),
                ('manifestation_creation_date', models.DateField(blank=True, null=True)),
                ('manifestation_creation_date_gregorian', models.DateField(blank=True, null=True)),
                ('manifestation_creation_date_year', models.IntegerField(blank=True, null=True)),
                ('manifestation_creation_date_month', models.IntegerField(blank=True, null=True)),
                ('manifestation_creation_date_day', models.IntegerField(blank=True, null=True)),
                ('manifestation_creation_date_inferred', models.SmallIntegerField()),
                ('manifestation_creation_date_uncertain', models.SmallIntegerField()),
                ('manifestation_creation_date_approx', models.SmallIntegerField()),
                ('manifestation_is_translation', models.SmallIntegerField()),
                ('language_of_manifestation', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('manifestation_incipit', models.TextField(blank=True, null=True)),
                ('manifestation_excipit', models.TextField(blank=True, null=True)),
                ('manifestation_ps', models.TextField(blank=True, null=True)),
                ('creation_timestamp', models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True)),
                ('creation_user', models.CharField(max_length=50)),
                ('change_timestamp', models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True)),
                ('change_user', models.CharField(max_length=50)),
                ('manifestation_creation_date2_year', models.IntegerField(blank=True, null=True)),
                ('manifestation_creation_date2_month', models.IntegerField(blank=True, null=True)),
                ('manifestation_creation_date2_day', models.IntegerField(blank=True, null=True)),
                ('manifestation_creation_date_is_range', models.SmallIntegerField()),
                ('manifestation_creation_date_as_marked', models.CharField(blank=True, max_length=250, null=True)),
                ('opened', models.CharField(max_length=3)),
                ('uuid', models.UUIDField(blank=True, null=True)),
                ('routing_mark_stamp', models.TextField(blank=True, null=True)),
                ('routing_mark_ms', models.TextField(blank=True, null=True)),
                ('handling_instructions', models.TextField(blank=True, null=True)),
                ('stored_folded', models.CharField(blank=True, max_length=20, null=True)),
                ('postage_costs_as_marked', models.CharField(blank=True, max_length=500, null=True)),
                ('postage_costs', models.CharField(blank=True, max_length=500, null=True)),
                ('non_delivery_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('date_of_receipt_as_marked', models.CharField(blank=True, max_length=500, null=True)),
                ('manifestation_receipt_calendar', models.CharField(max_length=2)),
                ('manifestation_receipt_date', models.DateField(blank=True, null=True)),
                ('manifestation_receipt_date_gregorian', models.DateField(blank=True, null=True)),
                ('manifestation_receipt_date_year', models.IntegerField(blank=True, null=True)),
                ('manifestation_receipt_date_month', models.IntegerField(blank=True, null=True)),
                ('manifestation_receipt_date_day', models.IntegerField(blank=True, null=True)),
                ('manifestation_receipt_date_inferred', models.SmallIntegerField()),
                ('manifestation_receipt_date_uncertain', models.SmallIntegerField()),
                ('manifestation_receipt_date_approx', models.SmallIntegerField()),
                ('manifestation_receipt_date2_year', models.IntegerField(blank=True, null=True)),
                ('manifestation_receipt_date2_month', models.IntegerField(blank=True, null=True)),
                ('manifestation_receipt_date2_day', models.IntegerField(blank=True, null=True)),
                ('manifestation_receipt_date_is_range', models.SmallIntegerField()),
                ('accompaniments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cofk_union_manifestation',
            },
            bases=(models.Model, core.helper.model_utils.RecordTracker),
        ),
        migrations.CreateModel(
            name='CofkCollectImageOfManif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifestation_id', models.IntegerField()),
                ('image_filename', models.CharField(max_length=2000)),
                ('_id', models.CharField(blank=True, max_length=32, null=True)),
                ('iwork_id', models.IntegerField(blank=True, null=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='uploader.cofkcollectupload')),
            ],
            options={
                'db_table': 'cofk_collect_image_of_manif',
            },
        ),
        migrations.CreateModel(
            name='CofkCollectManifestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifestation_id', models.IntegerField()),
                ('manifestation_type', models.CharField(max_length=3)),
                ('id_number_or_shelfmark', models.CharField(blank=True, max_length=500, null=True)),
                ('printed_edition_details', models.TextField(blank=True, null=True)),
                ('manifestation_notes', models.TextField(blank=True, null=True)),
                ('image_filenames', models.TextField(blank=True, null=True)),
                ('upload_name', models.CharField(blank=True, max_length=254, null=True)),
                ('_id', models.CharField(blank=True, max_length=32, null=True)),
                ('iwork', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='work.cofkcollectwork')),
                ('repository', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='institution.cofkcollectinstitution')),
                ('union_manifestation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manifestation.cofkunionmanifestation')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.cofkcollectupload')),
            ],
            options={
                'db_table': 'cofk_collect_manifestation',
                'unique_together': {('upload', 'iwork_id', 'manifestation_id')},
            },
        ),
        migrations.CreateModel(
            name='CofkUnionLanguageOfManifestation',
            fields=[
                ('manifestation', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='manifestation.cofkunionmanifestation')),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
                ('language_code', models.ForeignKey(db_column='language_code', on_delete=django.db.models.deletion.DO_NOTHING, to='uploader.iso639languagecode')),
            ],
            options={
                'db_table': 'cofk_union_language_of_manifestation',
                'unique_together': {('manifestation', 'language_code')},
            },
        ),
    ]
