# Generated by Django 4.0.5 on 2022-06-28 10:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CofkUnionManifestation',
            fields=[
                ('manifestation_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('manifestation_type', models.CharField(default='', max_length=3)),
                ('id_number_or_shelfmark', models.CharField(max_length=500)),
                ('printed_edition_details', models.TextField()),
                ('paper_size', models.CharField(max_length=500)),
                ('paper_type_or_watermark', models.CharField(max_length=500)),
                ('number_of_pages_of_document', models.IntegerField()),
                ('number_of_pages_of_text', models.IntegerField()),
                ('seal', models.CharField(max_length=500)),
                ('postage_marks', models.CharField(max_length=500)),
                ('endorsements', models.TextField()),
                ('non_letter_enclosures', models.TextField()),
                ('manifestation_creation_calendar', models.CharField(default='U', max_length=2)),
                ('manifestation_creation_date', models.DateField()),
                ('manifestation_creation_date_gregorian', models.DateField()),
                ('manifestation_creation_date_year', models.IntegerField()),
                ('manifestation_creation_date_month', models.IntegerField()),
                ('manifestation_creation_date_day', models.IntegerField()),
                ('manifestation_creation_date_inferred', models.SmallIntegerField(default=0)),
                ('manifestation_creation_date_uncertain', models.SmallIntegerField(default=0)),
                ('manifestation_creation_date_approx', models.SmallIntegerField(default=0)),
                ('manifestation_is_translation', models.SmallIntegerField(default=0)),
                ('language_of_manifestation', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('manifestation_incipit', models.TextField()),
                ('manifestation_excipit', models.TextField()),
                ('manifestation_ps', models.TextField()),
                ('creation_timestamp', models.DateTimeField(auto_now=True)),
                ('change_timestamp', models.DateTimeField(auto_now=True)),
                ('manifestation_creation_date2_year', models.IntegerField()),
                ('manifestation_creation_date2_month', models.IntegerField()),
                ('manifestation_creation_date2_day', models.IntegerField()),
                ('manifestation_creation_date_is_range', models.SmallIntegerField(default=0)),
                ('manifestation_creation_date_as_marked', models.CharField(max_length=250)),
                ('opened', models.CharField(default='o', max_length=3)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('routing_mark_stamp', models.TextField()),
                ('routing_mark_ms', models.TextField()),
                ('handling_instructions', models.TextField()),
                ('stored_folded', models.CharField(max_length=20)),
                ('postage_costs_as_marked', models.CharField(max_length=500)),
                ('postage_costs', models.CharField(max_length=500)),
                ('non_delivery_reason', models.CharField(max_length=500)),
                ('date_of_receipt_as_marked', models.CharField(max_length=500)),
                ('manifestation_receipt_calendar', models.CharField(default='U', max_length=2)),
                ('manifestation_receipt_date', models.DateField()),
                ('manifestation_receipt_date_gregorian', models.DateField()),
                ('manifestation_receipt_date_year', models.IntegerField()),
                ('manifestation_receipt_date_month', models.IntegerField()),
                ('manifestation_receipt_date_day', models.IntegerField()),
                ('manifestation_receipt_date_inferred', models.SmallIntegerField(default=0)),
                ('manifestation_receipt_date_uncertain', models.SmallIntegerField(default=0)),
                ('manifestation_receipt_date_approx', models.SmallIntegerField(default=0)),
                ('manifestation_receipt_date2_year', models.IntegerField()),
                ('manifestation_receipt_date2_month', models.IntegerField()),
                ('manifestation_receipt_date2_day', models.IntegerField()),
                ('manifestation_receipt_date_is_range', models.SmallIntegerField(default=0)),
                ('accompaniments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CofkUnionLanguageOfManifestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=100)),
                ('language_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.iso639languagecode')),
                ('manifestation_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manifestation.cofkunionmanifestation')),
            ],
        ),
        migrations.CreateModel(
            name='CofkCollectManifestation',
            fields=[
                ('manifestation_id', models.AutoField(primary_key=True, serialize=False)),
                ('manifestation_type', models.CharField(default='', max_length=3)),
                ('repository_id', models.IntegerField()),
                ('id_number_or_shelfmark', models.CharField(max_length=500)),
                ('printed_edition_details', models.TextField()),
                ('manifestation_notes', models.TextField()),
                ('image_filenames', models.TextField()),
                ('upload_name', models.CharField(max_length=254)),
                ('_id', models.CharField(max_length=32)),
                ('union_manifestation_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='manifestation.cofkunionmanifestation')),
                ('upload_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.cofkcollectupload')),
            ],
        ),
    ]
