# Generated by Django 4.0.6 on 2022-09-01 13:00

import core.helper.model_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifestation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkunionmanifestation',
            name='change_timestamp',
            field=models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True),
        ),
        migrations.AlterField(
            model_name='cofkunionmanifestation',
            name='creation_timestamp',
            field=models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True),
        ),
    ]
