# Generated by Django 4.0.6 on 2022-10-17 14:12

import core.helper.model_utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_cofkworklocationmap'),
        ('core', '0001_initial'),
        ('manifestation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cofkunionmanifestation',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.cofkunionwork'),
        ),
        migrations.CreateModel(
            name='CofkManifCommentMap',
            fields=[
                ('recref_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_date', models.DateField(null=True)),
                ('to_date', models.DateField(null=True)),
                ('relationship_type', models.CharField(max_length=100)),
                ('creation_timestamp', models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True)),
                ('creation_user', models.CharField(max_length=50)),
                ('change_timestamp', models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True)),
                ('change_user', models.CharField(max_length=50)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cofkunioncomment')),
                ('manifestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manifestation.cofkunionmanifestation')),
            ],
            options={
                'db_table': 'cofk_manif_comment_map',
                'abstract': False,
            },
            bases=(models.Model, core.helper.model_utils.RecordTracker),
        ),
    ]
