# Generated by Django 4.0.6 on 2022-07-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifestation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkcollectmanifestation',
            name='repository_id',
            field=models.IntegerField(null=True),
        ),
    ]
