# Generated by Django 4.0.6 on 2022-10-20 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_set_default_values'),
        ('manifestation', '0002_create_seq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkunionlanguageofmanifestation',
            name='language_code',
            field=models.ForeignKey(db_column='code_639_3', on_delete=django.db.models.deletion.DO_NOTHING, to='uploader.iso639languagecode'),
        ),
    ]
