# Generated by Django 4.0.6 on 2022-09-22 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_remove_cofkcollectaddresseeofwork_iperson_id_and_more'),
        ('uploader', '0005_alter_iso639languagecode_table'),
        ('institution', '0003_cofkcollectinstitution_id_and_more'),
        ('manifestation', '0002_alter_cofkunionmanifestation_change_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cofkcollectmanifestation',
            name='iwork_id',
        ),
        migrations.RemoveField(
            model_name='cofkcollectmanifestation',
            name='repository_id',
        ),
        migrations.AddField(
            model_name='cofkcollectmanifestation',
            name='iwork',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='work.cofkcollectwork'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cofkcollectmanifestation',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='institution.cofkcollectinstitution'),
        ),
        migrations.AlterField(
            model_name='cofkcollectmanifestation',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.cofkcollectupload'),
        ),
    ]
