# Generated by Django 4.0.6 on 2022-10-17 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manifestation', '0002_cofkunionmanifestation_work_cofkmanifcommentmap'),
        ('manifestation', '0002_create_seq'),
    ]

    operations = [
    ]
