# Generated by Django 4.0.6 on 2022-10-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifestation', '0003_merge_20221017_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkunionmanifestation',
            name='manifestation_creation_calendar',
            field=models.CharField(default='U', max_length=2),
        ),
        migrations.AlterField(
            model_name='cofkunionmanifestation',
            name='manifestation_creation_date_approx',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cofkunionmanifestation',
            name='manifestation_creation_date_inferred',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cofkunionmanifestation',
            name='manifestation_creation_date_uncertain',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cofkunionmanifestation',
            name='manifestation_is_translation',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cofkunionmanifestation',
            name='manifestation_receipt_date_approx',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cofkunionmanifestation',
            name='manifestation_receipt_date_inferred',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cofkunionmanifestation',
            name='manifestation_receipt_date_is_range',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cofkunionmanifestation',
            name='manifestation_receipt_date_uncertain',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cofkunionmanifestation',
            name='manifestation_type',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='cofkunionmanifestation',
            name='opened',
            field=models.CharField(default='o', max_length=3),
        ),
    ]
