# Generated by Django 4.0.6 on 2022-12-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sync_old_schema'),
        ('manifestation', '0003_sync_old_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkunionmanifestation',
            name='images',
            field=models.ManyToManyField(through='manifestation.CofkManifImageMap', to='core.cofkunionimage'),
        ),
    ]
