# Generated by Django 4.0.6 on 2022-10-20 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_alter_iso639languagecode_code_639_3'),
        ('manifestation', '0003_alter_cofkunionlanguageofmanifestation_language_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkunionlanguageofmanifestation',
            name='language_code',
            field=models.ForeignKey(db_column='language_code', on_delete=django.db.models.deletion.DO_NOTHING, to='uploader.iso639languagecode', to_field='code_639_3'),
        ),
    ]
