# Generated by Django 4.0.6 on 2023-03-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_cofklookupcatalogue_options_and_more'),
        ('manifestation', '0003_sync_old_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='cofkunionmanifestation',
            name='comments',
            field=models.ManyToManyField(through='manifestation.CofkManifCommentMap', to='core.cofkunioncomment'),
        ),
    ]
