# Generated by Django 4.0.6 on 2023-05-15 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_delete_cofkunionqueryablework'),
        ('manifestation', '0004_cofkunionmanifestation_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkmanifinstmap',
            name='manif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cofkmanifinstmap_set', to='manifestation.cofkunionmanifestation'),
        ),
        migrations.AlterField(
            model_name='cofkunionmanifestation',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manif_set', to='work.cofkunionwork'),
        ),
    ]
