# Generated by Django 4.0.6 on 2023-05-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifestation', '0004_cofkunionmanifestation_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkunionmanifestation',
            name='manifestation_creation_date_is_range',
            field=models.SmallIntegerField(default=0),
        ),
    ]
