# Generated by Django 4.0.6 on 2022-10-18 14:58

import core.helper.model_utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_create_seq'),
        ('manifestation', '0004_alter_cofkunionmanifestation_manifestation_creation_calendar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CofkManifPersonMap',
            fields=[
                ('recref_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_date', models.DateField(null=True)),
                ('to_date', models.DateField(null=True)),
                ('relationship_type', models.CharField(max_length=100)),
                ('creation_timestamp', models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True)),
                ('creation_user', models.CharField(max_length=50)),
                ('change_timestamp', models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True)),
                ('change_user', models.CharField(max_length=50)),
                ('manifestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manifestation.cofkunionmanifestation')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.cofkunionperson')),
            ],
            options={
                'db_table': 'cofk_manif_person_map',
                'abstract': False,
            },
            bases=(models.Model, core.helper.model_utils.RecordTracker),
        ),
    ]
