# Generated by Django 4.0.6 on 2022-10-19 03:55

import core.helper.model_utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manifestation', '0005_cofkmanifpersonmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='CofkManifManifMap',
            fields=[
                ('recref_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_date', models.DateField(null=True)),
                ('to_date', models.DateField(null=True)),
                ('relationship_type', models.CharField(max_length=100)),
                ('creation_timestamp', models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True)),
                ('creation_user', models.CharField(max_length=50)),
                ('change_timestamp', models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True)),
                ('change_user', models.CharField(max_length=50)),
                ('manif_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manif_from_set', to='manifestation.cofkunionmanifestation')),
                ('manif_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manif_to_set', to='manifestation.cofkunionmanifestation')),
            ],
            options={
                'db_table': 'cofk_manif_manif_map',
                'abstract': False,
            },
            bases=(models.Model, core.helper.model_utils.RecordTracker),
        ),
    ]
