# Generated by Django 4.0.6 on 2023-05-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifestation', '0005_alter_cofkmanifinstmap_manif_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cofkmanifcommentmap',
            index=models.Index(fields=['manifestation', 'relationship_type'], name='cofk_manif__manifes_fc98cc_idx'),
        ),
        migrations.AddIndex(
            model_name='cofkmanifimagemap',
            index=models.Index(fields=['manif', 'relationship_type'], name='cofk_manif__manif_i_3d4be5_idx'),
        ),
        migrations.AddIndex(
            model_name='cofkmanifinstmap',
            index=models.Index(fields=['manif', 'relationship_type'], name='cofk_manif__manif_i_72ed31_idx'),
        ),
        migrations.AddIndex(
            model_name='cofkmanifmanifmap',
            index=models.Index(fields=['manif_from', 'relationship_type'], name='cofk_manif__manif_f_3e5138_idx'),
        ),
        migrations.AddIndex(
            model_name='cofkmanifmanifmap',
            index=models.Index(fields=['manif_to', 'relationship_type'], name='cofk_manif__manif_t_95cd94_idx'),
        ),
        migrations.AddIndex(
            model_name='cofkmanifpersonmap',
            index=models.Index(fields=['manifestation', 'relationship_type'], name='cofk_manif__manifes_43dfd9_idx'),
        ),
    ]
