# Generated by Django 4.0.6 on 2023-05-18 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manifestation', '0005_alter_cofkunionmanifestation_manifestation_creation_date_is_range'),
        ('manifestation', '0006_cofkmanifcommentmap_cofk_manif__manifes_fc98cc_idx_and_more'),
    ]

    operations = [
    ]
