# Generated by Django 5.2.15 on 2026-07-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifestation', '0008_alter_cofkunionlanguageofmanifestation_language_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkmanifcommentmap',
            name='change_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofkmanifcommentmap',
            name='creation_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofkmanifimagemap',
            name='change_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofkmanifimagemap',
            name='creation_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofkmanifinstmap',
            name='change_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofkmanifinstmap',
            name='creation_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofkmanifmanifmap',
            name='change_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofkmanifmanifmap',
            name='creation_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofkmanifpersonmap',
            name='change_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofkmanifpersonmap',
            name='creation_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofkunionmanifestation',
            name='change_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofkunionmanifestation',
            name='creation_user',
            field=models.CharField(max_length=254),
        ),
    ]
