
recref_left_right_list = [
    ('refers_to', 'comment', 'location'),
    ('refers_to', 'comment', 'manifestation'),
    ('refers_to_date', 'comment', 'manifestation'),
    ('refers_to_receipt_date', 'comment', 'manifestation'),
    ('refers_to', 'comment', 'person'),
    ('refers_to', 'comment', 'work'),
    ('refers_to_addressee', 'comment', 'work'),
    ('refers_to_author', 'comment', 'work'),
    ('refers_to_date', 'comment', 'work'),
    ('refers_to_destination', 'comment', 'work'),
    ('refers_to_origin', 'comment', 'work'),
    ('refers_to_people_mentioned_in_work', 'comment', 'work'),
    ('route', 'comment', 'work'),
    ('image_of', 'image', 'manif'),
    ('image_of', 'image', 'person'),
    ('is_related_to', 'institution', 'resource'),
    ('is_related_to', 'location', 'resource'),
    ('stored_in', 'manif', 'inst'),
    ('enclosed_in', 'manif_from', 'manif_to'),
    ('is_manifestation_of', 'manif', 'work'),
    ('died_at_location', 'person', 'location'),
    ('was_born_in_location', 'person', 'location'),
    ('was_in_location', 'person', 'location'),
    ('formerly_owned','person', 'manifestation'),
    ('handwrote','person', 'manifestation'),
    ('partly_handwrote','person', 'manifestation'),
    ('acquaintance_of', 'related', 'person'),
    ('collaborated_with', 'related', 'person'),
    ('colleague_of', 'related', 'person'),
    ('employed', 'person', 'related'),
    ('friend_of', 'related', 'person'),
    ('member_of', 'person', 'related',),
    ('parent_of', 'person', 'related'),
    ('relative_of', 'related', 'person'),
    ('sibling_of', 'related', 'person'),
    ('spouse_of', 'related', 'person'),
    ('taught', 'person', 'related'),
    ('unspecified_relationship_with', 'related', 'person'),
    ('was_patron_of', 'person', 'related'),
    ('is_related_to', 'person', 'resource'),
    ('member_of', 'person', 'role'),
    ('created', 'person', 'work'),
    ('signed', 'person', 'work'),
    ('mentions_place', 'work', 'location'),
    ('was_sent_from', 'work', 'location'),
    ('was_sent_to', 'work', 'location'),
    ('intended_for', 'work', 'person'),
    ('mentions', 'work', 'person'),
    ('was_addressed_to', 'work', 'person'),
    ('is_related_to', 'work', 'resource'),
    ('deals_with', 'work', 'subject'),
    ('is_reply_to', 'work_from', 'work_to'),
    ('matches', 'work_from', 'work_to'),
    ('mentions_work', 'work_from', 'work_to'),
]
