# Generated by Django 4.0.6 on 2022-08-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cofkunionperson',
            name='roles',
            field=models.ManyToManyField(to='uploader.cofkunionrolecategory'),
        ),
    ]
