# Generated by Django 4.0.6 on 2022-11-14 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_create_seq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cofkpersonpersonmap',
            name='person_type',
        ),
    ]
