# Generated by Django 4.0.6 on 2022-09-09 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_cofkunionperson_roles'),
        ('person', '0002_create_seq'),
    ]

    operations = [
    ]
