# Generated by Django 4.0.6 on 2022-09-09 09:53

import core.helper.model_utils
from django.db import migrations, models
import django.db.models.deletion
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_cofkunionlocation_change_timestamp_and_more'),
        ('person', '0003_merge_0002_cofkunionperson_roles_0002_create_seq'),
    ]

    operations = [
        migrations.CreateModel(
            name='CofkPersonLocationMap',
            fields=[
                ('recref_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_date', models.DateField(null=True)),
                ('to_date', models.DateField(null=True)),
                ('relationship_type', models.CharField(max_length=100)),
                ('creation_timestamp', models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True)),
                ('creation_user', models.CharField(max_length=50)),
                ('change_timestamp', models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True)),
                ('change_user', models.CharField(max_length=50)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.cofkunionlocation')),
            ],
            options={
                'db_table': 'cofk_person_location_map',
                'abstract': False,
            },
            bases=(models.Model, core.helper.model_utils.RecordTracker),
        ),
        migrations.AddField(
            model_name='cofkunionperson',
            name='locations',
            field=models.ManyToManyField(through='person.CofkPersonLocationMap', to='location.cofkunionlocation'),
        ),
        migrations.AlterField(
            model_name='cofkunionperson',
            name='change_timestamp',
            field=models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True),
        ),
        migrations.AlterField(
            model_name='cofkunionperson',
            name='creation_timestamp',
            field=models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True),
        ),
        migrations.AlterField(
            model_name='cofkunionperson',
            name='iperson_id',
            field=models.IntegerField(default=functools.partial(core.helper.model_utils.next_seq_safe, *('cofk_union_person_iperson_id_seq',), **{}), unique=True),
        ),
        migrations.CreateModel(
            name='CofkPersonPersonMap',
            fields=[
                ('recref_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_date', models.DateField(null=True)),
                ('to_date', models.DateField(null=True)),
                ('relationship_type', models.CharField(max_length=100)),
                ('creation_timestamp', models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True)),
                ('creation_user', models.CharField(max_length=50)),
                ('change_timestamp', models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True)),
                ('change_user', models.CharField(max_length=50)),
                ('person_type', models.CharField(default='other', max_length=100)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passive_relationships', to='person.cofkunionperson', to_field='iperson_id')),
                ('related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_relationships', to='person.cofkunionperson', to_field='iperson_id')),
            ],
            options={
                'db_table': 'cofk_person_person_map',
                'abstract': False,
            },
            bases=(models.Model, core.helper.model_utils.RecordTracker),
        ),
        migrations.AddField(
            model_name='cofkpersonlocationmap',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.cofkunionperson', to_field='iperson_id'),
        ),
    ]
