# Generated by Django 4.0.6 on 2022-09-01 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_create_seq'),
        ('person', '0003_alter_cofkunionperson_change_timestamp_and_more'),
    ]

    operations = [
    ]
