# Generated by Django 4.0.6 on 2022-11-15 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_remove_cofkpersonpersonmap_person_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cofkunionperson',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='cofkunionperson',
            name='resources',
        ),
    ]
