# Generated by Django 4.0.6 on 2023-01-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_alter_cofkunionqueryablework_work'),
        ('person', '0004_add_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='cofkunionperson',
            name='works',
            field=models.ManyToManyField(through='work.CofkWorkPersonMap', to='work.cofkunionwork'),
        ),
    ]
