# Generated by Django 4.0.6 on 2022-11-17 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_remove_cofkunionperson_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cofkunionperson',
            name='roles',
        ),
    ]
