# Generated by Django 4.0.6 on 2022-09-01 13:27

import core.helper.model_utils
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_merge_20220901_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkunionperson',
            name='iperson_id',
            field=models.IntegerField(default=functools.partial(core.helper.model_utils.next_seq_safe, *('cofk_union_person_iperson_id_seq',), **{})),
        ),
    ]
