# Generated by Django 4.0.6 on 2022-09-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cofkunioncomment_change_timestamp_and_more'),
        ('person', '0005_alter_cofkpersonpersonmap_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cofkunionperson',
            name='comments',
            field=models.ManyToManyField(to='core.cofkunioncomment'),
        ),
    ]
