# Generated by Django 4.0.6 on 2023-01-30 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_cofkunionperson_works'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkunionpersonsummary',
            name='iperson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='summary', serialize=False, to='person.cofkunionperson', to_field='iperson_id'),
        ),
    ]
