# Generated by Django 4.0.6 on 2022-09-06 13:52

import core.helper.model_utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_cofkunionlocation_change_timestamp_and_more'),
        ('person', '0005_alter_cofkunionperson_iperson_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CofkPersonLocationMap',
            fields=[
                ('person_location_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('relationship_type', models.CharField(max_length=100)),
                ('creation_timestamp', models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True)),
                ('creation_user', models.CharField(max_length=50)),
                ('change_timestamp', models.DateTimeField(blank=True, default=core.helper.model_utils.default_current_timestamp, null=True)),
                ('change_user', models.CharField(max_length=50)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.cofkunionlocation')),
            ],
            options={
                'db_table': 'cofk_person_location_map',
            },
            bases=(models.Model, core.helper.model_utils.RecordTracker),
        ),
        migrations.AddField(
            model_name='cofkunionperson',
            name='locations',
            field=models.ManyToManyField(through='person.CofkPersonLocationMap', to='location.cofkunionlocation'),
        ),
        migrations.AddField(
            model_name='cofkpersonlocationmap',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.cofkunionperson'),
        ),
    ]
