# Generated by Django 4.0.6 on 2022-09-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_cofkpersonlocationmap_cofkunionperson_locations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkpersonlocationmap',
            name='from_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cofkpersonlocationmap',
            name='to_date',
            field=models.DateField(null=True),
        ),
    ]
