# Generated by Django 4.0.6 on 2022-09-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cofkunioncomment_change_timestamp_and_more'),
        ('person', '0006_cofkunionperson_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='cofkunionperson',
            name='resources',
            field=models.ManyToManyField(to='core.cofkunionresource'),
        ),
    ]
