# Generated by Django 4.0.6 on 2023-03-06 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_cofklookupcatalogue_options_and_more'),
        ('person', '0006_alter_cofkunionpersonsummary_iperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='cofkunionperson',
            name='roles',
            field=models.ManyToManyField(related_name='person', through='person.CofkPersonRoleMap', to='core.cofkunionrolecategory'),
        ),
        migrations.AlterField(
            model_name='cofkunionperson',
            name='organisation_type',
            field=models.ForeignKey(blank=True, db_column='organisation_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='person', to='core.cofkunionorgtype'),
        ),
        migrations.DeleteModel(
            name='CofkUnionPersonSummary',
        ),
    ]
