# Generated by Django 4.0.6 on 2022-09-06 15:04

import core.helper.model_utils
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_alter_cofkpersonlocationmap_from_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkunionperson',
            name='iperson_id',
            field=models.IntegerField(default=functools.partial(core.helper.model_utils.next_seq_safe, *('cofk_union_person_iperson_id_seq',), **{}), unique=True),
        ),
    ]
