# Generated by Django 4.0.6 on 2022-09-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_delete_cofkunionpublication'),
        ('person', '0007_cofkunionperson_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='cofkunionperson',
            name='images',
            field=models.ManyToManyField(to='uploader.cofkunionimage'),
        ),
    ]
