# Generated by Django 4.0.6 on 2023-05-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_cofkunionperson_roles_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cofkpersoncommentmap',
            index=models.Index(fields=['person', 'relationship_type'], name='cofk_person_person__6401a1_idx'),
        ),
        migrations.AddIndex(
            model_name='cofkpersonimagemap',
            index=models.Index(fields=['person', 'relationship_type'], name='cofk_person_person__156355_idx'),
        ),
        migrations.AddIndex(
            model_name='cofkpersonlocationmap',
            index=models.Index(fields=['person', 'relationship_type'], name='cofk_person_person__94156c_idx'),
        ),
        migrations.AddIndex(
            model_name='cofkpersonpersonmap',
            index=models.Index(fields=['person', 'relationship_type'], name='cofk_person_person__4c7f5a_idx'),
        ),
        migrations.AddIndex(
            model_name='cofkpersonpersonmap',
            index=models.Index(fields=['related', 'relationship_type'], name='cofk_person_related_af6b9b_idx'),
        ),
        migrations.AddIndex(
            model_name='cofkpersonresourcemap',
            index=models.Index(fields=['person', 'relationship_type'], name='cofk_person_person__12e880_idx'),
        ),
        migrations.AddIndex(
            model_name='cofkpersonrolemap',
            index=models.Index(fields=['person', 'relationship_type'], name='cofk_person_person__40f54f_idx'),
        ),
    ]
