# Generated by Django 4.0.6 on 2023-06-14 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_cofkpersoncommentmap_cofk_person_person__6401a1_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayablePerson',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('person.cofkunionperson',),
        ),
        migrations.AlterModelOptions(
            name='cofkunionperson',
            options={'permissions': [('export_file', 'Export csv/excel from search results')]},
        ),
    ]
