# Generated by Django 4.0.6 on 2022-09-06 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_alter_cofkunionperson_iperson_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkpersonlocationmap',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.cofkunionperson', to_field='iperson_id'),
        ),
    ]
