# Generated by Django 4.0.6 on 2022-09-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_cofkunionperson_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkunionperson',
            name='date_of_birth_approx',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cofkunionperson',
            name='date_of_birth_inferred',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cofkunionperson',
            name='date_of_birth_is_range',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cofkunionperson',
            name='date_of_birth_uncertain',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cofkunionperson',
            name='date_of_death_approx',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cofkunionperson',
            name='date_of_death_inferred',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cofkunionperson',
            name='date_of_death_is_range',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cofkunionperson',
            name='date_of_death_uncertain',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cofkunionperson',
            name='flourished_approx',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cofkunionperson',
            name='flourished_inferred',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cofkunionperson',
            name='flourished_is_range',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cofkunionperson',
            name='flourished_uncertain',
            field=models.SmallIntegerField(default=0),
        ),
    ]
