# Generated by Django 4.0.6 on 2023-08-04 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_displayableperson_alter_cofkunionperson_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResultPerson',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('person.displayableperson',),
        ),
    ]
