# Generated by Django 4.0.6 on 2022-09-22 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0005_alter_iso639languagecode_table'),
        ('person', '0009_alter_cofkunionperson_date_of_birth_approx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkcollectperson',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.cofkcollectupload'),
        ),
    ]
