# Generated by Django 4.0.6 on 2022-09-29 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_alter_cofkunionperson_date_of_birth_approx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkpersonlocationmap',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.cofkunionperson'),
        ),
    ]
