# Generated by Django 4.0.6 on 2025-02-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0010_searchresultperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkunionperson',
            name='iperson_id',
            field=models.IntegerField(unique=True),
        ),
    ]
