# Generated by Django 4.0.6 on 2022-09-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0010_alter_cofkcollectperson_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkcollectperson',
            name='iperson_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
