# Generated by Django 4.0.6 on 2024-09-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0010_searchresultperson'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cofkunionperson',
            index=models.Index(fields=['iperson_id'], name='cofk_union__iperson_66e15a_idx'),
        ),
    ]
