# Generated by Django 5.2.15 on 2026-07-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_displayablelocation'),
        ('person', '0011_alter_cofkunionperson_iperson_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkunionperson',
            name='locations',
            field=models.ManyToManyField(through='person.CofkPersonLocationMap', through_fields=('person', 'location'), to='location.cofkunionlocation'),
        ),
    ]
