# Generated by Django 4.0.6 on 2024-09-24 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0011_cofkunionperson_cofk_union__iperson_66e15a_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cofkunionperson',
            options={'permissions': [('export_file', 'Export csv/excel from search results'), ('tombstone', 'Allow use tombstone feature to find similar records')]},
        ),
    ]
