# Generated by Django 5.2.15 on 2026-07-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_update_audit_literal_helpers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkunionauditliteral',
            name='change_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofkunionauditrelationship',
            name='change_user',
            field=models.CharField(max_length=254),
        ),
    ]
