# Generated by Django 4.0.6 on 2022-10-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkunionpublication',
            name='publication_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
