# Generated by Django 4.0.6 on 2022-10-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_alter_cofkunionpublication_publication_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkunionpublication',
            name='publication_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
