# Generated by Django 5.2.15 on 2026-07-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_sync_old_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkunionpublication',
            name='change_user',
            field=models.CharField(max_length=254),
        ),
    ]
