# Generated by Django 4.0.5 on 2022-06-28 10:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CofkUnionInstitution',
            fields=[
                ('institution_id', models.AutoField(primary_key=True, serialize=False)),
                ('institution_name', models.TextField(default='')),
                ('institution_synonyms', models.TextField(default='')),
                ('institution_city', models.TextField(default='')),
                ('institution_city_synonyms', models.TextField(default='')),
                ('institution_country', models.TextField(default='')),
                ('institution_country_synonyms', models.TextField(default='')),
                ('creation_timestamp', models.DateTimeField(auto_now=True)),
                ('change_timestamp', models.DateTimeField(auto_now=True)),
                ('editors_notes', models.TextField()),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('address', models.TextField()),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CofkCollectInstitutionResource',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False)),
                ('institution_id', models.IntegerField()),
                ('resource_name', models.TextField(default='')),
                ('resource_details', models.TextField(default='')),
                ('resource_url', models.TextField(default='')),
                ('upload_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='uploader.cofkcollectupload')),
            ],
        ),
        migrations.CreateModel(
            name='CofkCollectInstitution',
            fields=[
                ('institution_id', models.AutoField(primary_key=True, serialize=False)),
                ('institution_name', models.TextField(default='')),
                ('institution_city', models.TextField(default='')),
                ('institution_country', models.TextField(default='')),
                ('upload_name', models.CharField(max_length=254)),
                ('_id', models.CharField(max_length=32)),
                ('institution_synonyms', models.TextField()),
                ('institution_city_synonyms', models.TextField()),
                ('institution_country_synonyms', models.TextField()),
                ('union_institution_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='institution.cofkunioninstitution')),
                ('upload_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.cofkcollectupload')),
            ],
        ),
    ]
