# Generated by Django 4.0.6 on 2022-10-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cofkunioninstitution',
            name='resources',
            field=models.ManyToManyField(to='core.cofkunionresource'),
        ),
        migrations.AlterField(
            model_name='cofkunioninstitution',
            name='institution_city_synonyms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cofkunioninstitution',
            name='institution_country_synonyms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cofkunioninstitution',
            name='institution_synonyms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
