# Generated by Django 4.0.6 on 2022-07-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkcollectinstitution',
            name='institution_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
