# Generated by Django 4.0.6 on 2022-09-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_alter_cofkunioninstitution_change_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkcollectinstitution',
            name='institution_id',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='cofkcollectinstitution',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
