# Generated by Django 4.0.6 on 2023-05-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_sync_old_schema'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cofkinstitutionimagemap',
            index=models.Index(fields=['institution', 'relationship_type'], name='cofk_instit_institu_3ef504_idx'),
        ),
        migrations.AddIndex(
            model_name='cofkinstitutionresourcemap',
            index=models.Index(fields=['institution', 'relationship_type'], name='cofk_instit_institu_0a5a52_idx'),
        ),
    ]
