# Generated by Django 4.0.6 on 2022-11-30 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_cofkinstitutionresourcemap_cofkinstitutionimagemap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cofkunioninstitution',
            name='resources',
        ),
    ]
