# Generated by Django 4.0.6 on 2023-06-14 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_cofkinstitutionimagemap_cofk_instit_institu_3ef504_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cofkunioninstitution',
            options={'permissions': [('export_file', 'Export csv/excel from search results')]},
        ),
    ]
