# Generated by Django 5.2.15 on 2026-07-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0004_alter_cofkunioninstitution_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofkinstitutionimagemap',
            name='change_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofkinstitutionimagemap',
            name='creation_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofkinstitutionresourcemap',
            name='change_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofkinstitutionresourcemap',
            name='creation_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofkunioninstitution',
            name='change_user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cofkunioninstitution',
            name='creation_user',
            field=models.CharField(max_length=254),
        ),
    ]
