# Generated by Django 4.0.6 on 2025-06-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0004_alter_cofkunioninstitution_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cofkunioninstitution',
            name='is_tombstone',
            field=models.BooleanField(default=False, help_text='Mark as tombstone instead of deleting'),
        ),
    ]
