# Generated by Django 4.0.6 on 2024-10-02 11:10

from django.db import migrations, models

import core.helper.model_serv


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClonefinderRequest',
            fields=[
                ('clonefinder_req_id', models.AutoField(primary_key=True, serialize=False)),
                ('sql', models.TextField(blank=True, null=True)),
                ('sql_params', models.BinaryField(blank=True, null=True)),
                ('result_jsonl', models.TextField(blank=True, null=True)),
                ('status', models.SmallIntegerField(default=0)),
                ('model_name', models.CharField(max_length=100)),
                ('creation_timestamp', models.DateTimeField(blank=True, default=core.helper.model_serv.default_current_timestamp, null=True)),
                ('creation_user', models.CharField(max_length=50)),
                ('change_timestamp', models.DateTimeField(blank=True, default=core.helper.model_serv.default_current_timestamp, null=True)),
                ('change_user', models.CharField(max_length=50)),
            ],
            bases=(models.Model, core.helper.model_serv.RecordTracker),
        ),
    ]
